### ISSUE TITLE
package.yml und weitere Dateien :: author richtig benennen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mform#103]
Die Angabe des Authors entspricht nicht dem FOR-Standard. So soll es sein:
`author: Friends Of REDAXO`

Siehe dazu https://friendsofredaxo.github.io/info#ein-addon-zu-den-friends-of-redaxo-übertragen (Punkt 2). Wir machen das deshalb, damit alle FOR-AddOns einheitlich markiert sind, vor allem im Installer.

**Comment by joachimdoerr** [comment]
In der yml sollte das schon passen: https://github.com/FriendsOfREDAXO/mform/blob/master/package.yml#L4

**Comment by tbaddade** [comment]
> In der yml sollte das schon passen:

nicht ganz, siehe https://github.com/FriendsOfREDAXO/mform/blob/master/plugins/docs/package.yml

**Comment by joachimdoerr** [comment]
done. https://github.com/FriendsOfREDAXO/mform/commit/f9d04869c7bb68a8b1c55bb8a626286cfc8b303d
