### ISSUE TITLE
data/templates/ in generatecss.php

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/mform#105]
Hallo, ich bekomme im Systemlog immer Fehlermeldungen das er den Template Ordner nicht findet bei mform 4.2.3. Wenn ich die generatecss.php ändere passt es .
Zeile 38, 39, 41 aus   /templates/...   wird   data/templates/...   dann passt es zumindest bei mir.

**Comment by joachimdoerr** [comment]
Kann ich leider nicht nachstellen, kannst du das mal mit der aktuellen Git version testen?

**Comment by mbodon** [comment]
Guten Morgen, ich hatte ja geschrieben in der Version 4.2.3. - bei der 5erBeta hatte ich es nicht mehr aber die 5er wollte ich noch nicht auf Live-Systeme installieren ...  Ist den die Beta schon "stabil"  und kompatibel mit mform4x?

**Comment by mbodon** [comment]
![bildschirmfoto 2017-03-07 um 09 19 00](https://cloud.githubusercontent.com/assets/2822717/23647643/20828dea-0317-11e7-8c02-440c1eb8a01a.jpg)

**Comment by joachimdoerr** [comment]
Die 5er müsste kompatible sein, ich würde dir aber raten das vorher local zu testen damit du auch auf der sichern seite bist. ich hab jetzt begonnen ein changelog zu führen, den werd ich als bald commiten. für die v4 wird es keinen fix mehr geben, das problem ist ja mit der v5 behoben. der nächste release wird ziemlich bald statt finden.
