### ISSUE TITLE
leerzeichen fehlen

### ISSUE THREAD

**Issue by RexDude** [FriendsOfREDAXO/mform#106]
prob ist wieder da. hier fehlt ein leerzeichen vor dem checkt und selected. firefox zeigt die stellen rot und fett im code = kein gültiges html.

original mform ausgabe:
`<input id="rv2_8" type="checkbox" name="REX_INPUT_VALUE[8]" value="img-floater"checked="checked">`

`<option value="nolink"selected>`

**Comment by joachimdoerr** [comment]
Sollte hiermit gefixt sein https://github.com/FriendsOfREDAXO/mform/commit/4db250c7af1a86c2655b6637dd07279a1716e6b5
