### ISSUE TITLE
Keine Abstände zwischen den Zeilen

### ISSUE THREAD

**Issue by RexDude** [FriendsOfREDAXO/mform#109]
Ist das bei euch nicht?

![tabs](https://cloud.githubusercontent.com/assets/2674480/23868530/1144da14-0820-11e7-982c-3b52f04c7108.jpg)

```php
<?php
$mform = new MForm();

// tab
$mform->addTab('Bild');

// field
$mform->addMediaField(1);
$mform->setLabel('Bild');

// field
$mform->addSelectField(2);
$mform->setLabel('Ausrichtung');

// field
$mform->addSelectField(3);
$mform->setLabel('Bildtyp');


echo $mform->show();
?>
```

Ohne Tabs sind die Abstände normal da.

**Comment by RexDude** [comment]
ein overflow: hidden auf .form-group behebt das prob.

**Comment by skerbis** [comment]
der Fehler liegt wohl im default-theme, ich kann das auch außerhalb von mform reproduzieren

**Comment by skerbis** [comment]
@joachimdoerr @RexDude Hier fehlt ein Wapper-Div mit .form-horizontal im Tab
der Haupt-Stil muss nicht angepasst werden. Nur im Tab muss dieser Wrapper rein. 
Das gilt für alle Ausgaben von mform, auch ohne tabs
 
<img width="890" alt="bildschirmfoto 2017-03-13 um 20 08 51" src="https://cloud.githubusercontent.com/assets/791247/23871063/27c286a2-0829-11e7-80dc-c55ceeba44d1.png">

**Comment by skerbis** [comment]
.form-horizontal einfach in das form-div packen hilft

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/mform/pull/110

**Comment by RexDude** [comment]
Hab deinen Pull getestet ud läuft :) :+1:
