### ISSUE TITLE
Styling: Selects mit class="selectpicker" stylen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mform#111]
Da Redaxo von Haus aus Bootstrap-Select mitliefert kann man die Selects schöner darstellen. 
Hierzu class="selectpicker" setzen 
Beipie
<img width="904" alt="bildschirmfoto 2017-03-13 um 22 37 43" src="https://cloud.githubusercontent.com/assets/791247/23876427/c24084f4-083d-11e7-8832-0e4ba26e9815.png">
l

**Comment by joachimdoerr** [comment]
die frage ist ob MForm das default liefern sollte

**Comment by skerbis** [comment]
na ja man kann auch die class und Attrivbte übergeben. Dadurch hat man tatsächlich mehr Spielmöglichkeiten. z.B. eine Live-Search per data-live-search="true". 
Vielleicht was für die Doku?

**Comment by joachimdoerr** [comment]
das in jedem fall, und willst du das ggf in der doku ergänzen - es gibt ja diverse tricks die in die doku müssten...

**Comment by skerbis** [comment]
Wird in Tricks veröffentlicht
