### ISSUE TITLE
Multiselect ohne JSON

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/mform#112]
Hallo, ich versuche gerade ein Multiselect anzulegen das mit dann die "normalen" Werte liefert und nicht die JSON... das ist mein Aufruf $mform->addMultiSelectField(4,$linkzukategorie,array('label'=>'Link zu den Kategorien'), ‘full’); dabei ist $linkzukategorie ein Array mit den Werten... das Ergebnis ist aber JSON obwohl ich nicht addMultiSelectField("4" ...  benütze.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/blob/master/CHANGELOG.md
MForm ist hier auf die Standard Redaxo Multiple-Select Funktionalität umgestellt worden.

**Comment by skerbis** [comment]
Thema wurde in Slack geklärt.
