### ISSUE TITLE
bei addMediaField ist der Parameter 'types' case-sensitive

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/mform#114]
Soll heißen:
wenn ich schreibe: ```$mform->addMediaField("$id.0.image" ,array('types'=>'jpg' ....```
kann ich keine Datei namens "abc.JPG" hochladen.

**Comment by joachimdoerr** [comment]
hm das sollte doch eigentlich genau umgekehrt sein , wenn aktive dann sollte nur jpg nutzen können ggf. test mal 'types'=>'jpg,JPG'

**Comment by tyrant88** [comment]
Ja, ist schon klar, so hatte ich es schon aktuell ge-work-arounded. Aber das hies in dem Projekt, dass ich geerbt habe, alle Module durchsuchen und es in vier von 20 ändern.
Ich denke es wäre sinnvoll die Überprüfung case-insensitive zu machen, oder?

**Comment by joachimdoerr** [comment]
da wird lediglich die redaxo eigene Funktion genutzt, es wäre aber sinnvoll MForm so anzupassen, dass es automatisch "jpg" zu "jpg,JPG" mapt.

**Comment by tbaddade** [comment]
> da wird lediglich die redaxo eigene Funktion genutzt

`REX_MEDIA[id=1 widget=1 types=png]` liefert auch `PNG`

**Comment by joachimdoerr** [comment]
Close. 12d5df64d40dd54ac27b10b9e8bbbe2d70860d26 Space problem wurde gelöst, ein Problem mit case-sensitive kann ich nicht nachstellen.
