### ISSUE TITLE
CustomLink mit MailLink

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/mform#115]
Entweder ein eigener Button für einen E-Mail Link, oder aber im externen Link automatisch ein "mailto:" anhängen (mit Hinweis dazu wie zum Beispiel im Tiny) wäre cool.

**Comment by joachimdoerr** [comment]
ja wäre ein feature das es in mform-r4 auch schon gab. werd ich noch einbauen.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/2fbc8d2995f393c5f9470c7759d300a754f62f6e
