### ISSUE TITLE
addTab: letzte Position in Mblock

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/mform#117]
addTab speichert den letzten geöffneten Tab, so das dieser beim editieren des Moduls wieder angezeigt wird. Das ist auch super. In Zusammenhang mit Mblock haben alle Blockelemente die gleiche Tabposition, nämlich die des ersten Tabs.

**Comment by joachimdoerr** [comment]
Der Wunsch wäre, dass auch die Tabs in MBlock ihre jeweilige position merken?

**Comment by isospin** [comment]
Hmm, ich denk mal laut:
In meinem aktuellen Modul würde das Sinn machen, da ich die Tabs für alternative Inhalte nutze (Bild oder Text oder YForm Content). Wenn der Redakteur das Modul editiert ist bereits die aktuelle Position offen.

Auf der anderen Seite gibt es auch ganz andere Einsatzzwecke für die Tabs, bei denen die Position nicht relevant.

Aber da sich die Tabs bei der einfachen Verwendung (ohne MBLock) die Position merkt, würde ich das Verhalten auch in MBlock erwarten.

**Comment by isospin** [comment]
Bei der Nutzung des obigen MBlock Moduls ist mir gerade aufgefallen, das immer nur die Tabs im ersten Block umgeschaltet werden.

**Comment by joachimdoerr** [comment]
Das ist eher ein MBlock Issue, MForm nutzt die Default Bootstrap-Tabs, ich hab keine Ahnung wie man denen das entsprechend beibringt das die Position gemerkt oder nicht gemerkt wird. Ggf. Gibts jemand der davon mehr Ahnung hat als ich?

**Comment by joachimdoerr** [comment]
@ynamite ? Kannst Du dazu was sagen?

**Comment by ynamite** [comment]
Wie immer hab ich ne etwas längere Leitung ;) Was ist addTab? Ist das eine mblock/mform Methode?

Nur damit ich's richtig verstehe, wenn man einen Block editiert hat und dort ein bestimmtes Tab aktiv hatte, möchte man beim nächsten Editieren das zuletzt geöffnete Tab wieder aktiv/geöffnet haben? Selbst wenn man dazwischen andere Blöcke editiert hat?

**Comment by joachimdoerr** [comment]
@ynamite es ist eine MForm Methode, die sorgt dafür, dass man Tabs in Formulare nutzen kann - ähnlich wie man das mit MForm auch schon mit Fieldsets machen kann. 

Setzt man die in MBlock ein dann wirkt sich das Bootstrap-Memory der Tabs nur auf einen Tab aus nicht auf alle in allen Blöcken. Deswegen ist das eher eine MBlock als eine MForm Frage.

**Comment by ynamite** [comment]
@joachimdoerr ich selber nutze Bootstrap kaum (halt nur in Redaxo selbst), hab davon nicht viel Ahnung. 

Die Erwartung wäre, dass in jedem MBlock-Abschnitt (innerhalb eines einzigen Rex-Blocks) der zuvor ausgewählte Tab beim erneuten editieren des Modul-Blocks geöffnet ist? 

Wenn das Ganze weitgehend über die Bootstrap Tabs geht, müsste man schauen ob sich Bootstrap-Tabs die Positionen von mehreren Tabs auf der gleichen Seite merken können. Wenn nicht, wird's wahrscheinlich un poco complicado.

**Comment by joachimdoerr** [comment]
Ich schließe hier mal, der Wunsch ist so ohne weiteres nicht realisierbar.
