### ISSUE TITLE
theme.css wird nicht geladen

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/mform#118]
Hallo :)
Ich habe mich an einem eigenen Theme versucht, die .ini-Dateien mit dem gerüst frisst er auch, das funzt alles. Aber laut Chrome-Inspektor wird die theme.css nicht eingebunden und somit kann ich da reinschreiben was ich will - es passiert nix.

Redaxo 5.3. lädt bei mir alle Styles über style.css?buster=... vom Addon "be_style" und übergeht die theme.css!?

Wäre cool, wenn sich das ohne Workaround lösen ließe...

**Comment by joachimdoerr** [comment]
Ich check das mal ist sicher nichts großes danke fürs Issue

**Comment by joachimdoerr** [comment]
Hast du das Theme als default setting in MForm definiert? Oder im Modul Input dem Construktor beim initiieren mitgegeben?

**Comment by joachimdoerr** [comment]
Das Problem scheint beim Update von MForm aufzutauchen. Kann das jemand bestätigen?

**Comment by IngoWinter** [comment]
Ich hab seit Ewigkeiten ein eigenes Theme mit eigener theme.css und diese wird anstandslos geladen. Theme Dateien liegen im data Verzeichnis, Theme ist in den Einstellungen als Default gesetzt.

**Comment by joachimdoerr** [comment]
Ich schließe mal da das Problem nicht mehr reproduzierbar ist.
