### ISSUE TITLE
Validierung auf Systemelemente funktioniert nicht

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/mform#119]
Hallo Joachim,

folgendes wirst du durch einen Test leicht reproduzieren können...

```
### FUNKTIONIERT
$form->addInputField('text','1');
$form->setValidations(array(
	'empty' => '',
));

### FUNKTIONIERT NICHT
$form->addMediaField('1');
$form->setValidations(array(
	'empty' => '',
));
```

Wäre cool wenn das irgendwann mal eingebaut wird. Weil den Proof auf ein leeres MediaButton-Element brauche ich doch recht häufig... :)

Übrigens ist MForm ein Mega-AddOn - nutze es gerne und finde es logisch aufgebaut und effizient im Einsatz. Echt klasse :) Vielen Dank!

**Comment by joachimdoerr** [comment]
Ja die Validieren in SystemButtons ist noch nicht vorgesehen, ich muss mal schauen wie ich das am besten einbaue. Danke fürs Feedback, ggf. schaff ich das noch bis zum Redaxo Tag.

**Comment by joachimdoerr** [comment]
`<?php

$form = new MForm();

### FUNKTIONIERT
$form->addInputField('text','1');
$form->setValidations(array(
    'empty' => '',
));

### FUNKTIONIERT
$form->addMediaField('1');
$form->setValidations(array(
    'empty' => '',
));

### FUNKTIONIERT so lala -> weil empty nicht wirklich geeignet prüft ja nicht vorhandensein von options sondern nur ob eine selected
$form->addMedialistField('1');
$form->setValidations(array(
    'empty' => '',
));

### FUNKTIONIERT
$form->addLinkField('1');
$form->setValidations(array(
    'empty' => '',
));

### FUNKTIONIERT so lala -> weil empty nicht wirklich geeignet prüft ja nicht vorhandensein von options sondern nur ob eine selected
$form->addLinklistField('1');
$form->setValidations(array(
    'empty' => '',
));

### FUNKTIONIERT
$form->addCustomLinkField('2');
$form->setValidations(array(
    'empty' => '',
));

echo $form->show();

`
3cd9f06eb701bb39274757d1994bdba987ff3faf

**Comment by joachimdoerr** [comment]
Niemand ist fit -> schade... dann muss MForm eben ohne diese Validierung auskommen.

**Comment by georgkaser** [comment]
Jetzt hab ich eine Lösung die exakt dasselbe Verhalten hat wie die "readonly" Felder - vielleicht ist das ja ein Ansatz:

Im MForm Formular hab ich folgende Einstellungen vorgenommen (eine Klasse vergeben ging leider in MBlock nicht, deshalb das data-Attribut:

``` php
->addLinkField(1,array('label'=>'Link', 'class'=>'mediafield'))
    ->setAttribute('required', 'required')
    ->setAttribute('data-type', 'mediafield')
```
und dann noch etwas JavaScript und CSS hinzugefügt:

``` html
<script>
    var mediaFields = document.querySelectorAll("[data-type='mediafield']");
    for (var i = 0; i < mediaFields.length; i++) {
        mediaFields[i].removeAttribute('readonly');
        mediaFields[i].addEventListener('keypress', function(e) {
            e.preventDefault();
        });
    }
</script>
<style>
    input[data-type="mediafield"],
    input[data-type="mediafield"]:focus,
    input[data-type="mediafield"]:focus:not([readonly]) {
        cursor: text;
        caret-color: transparent;
        background-color: #e9ecf2;
    }
</style>
```
