### ISSUE TITLE
Tabs: Parameter

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mform#121]
Diese könnten benutzt werden um den Tabs ein Icon mitzugeben oder die Tabs z.B. rechtsbündig auszurichten

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/6ee125af958e651d2d48088e7508f28cc4a1b734

```
$mform->addTab('Tab1');
$mform->pullRight();
$mform->setTabIcon('fa-icon');
```
