### ISSUE TITLE
Tabs: Drag and Drop

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mform#122]
Ähnlich wie im EWS Modul (0010) der Modulsammlung

**Comment by olien** [comment]
http://www.jqueryscript.net/other/jQuery-Plugin-For-Dynamic-Bootstrap-Tabs-Component.html

**Comment by skerbis** [comment]
Ich denke das dies z.B. In Kombination mit Mblock Probleme verursachen wird. @joachimdoerr ?

**Comment by joachimdoerr** [comment]
Ja generell macht alles mit MBlock Probleme...

**Comment by skerbis** [comment]
close
