### ISSUE TITLE
Classes per Attribute übergeben funktioniert nicht

### ISSUE THREAD

**Issue by chrison94** [FriendsOfREDAXO/mform#123]
Hallo,

ich möchte gerne per 
`$mform->addCheckboxField(1,array(1=>'hide Controls'),array('label'=>'Checkbox', 'class'=>'hideControls'));`
der Checkbox eine Klasse mitgeben -> die Klasse wird aber nicht gesetzt - Label funktioniert aber!
Das Ganze basiert auf der aktuellen GitHub Variante

Grüße

**Comment by joachimdoerr** [comment]
Das sollte ins der neuen version 5.1.0 behoben sein. @chrison94 bitte nochmals testen und feedback geben.

**Comment by chrison94** [comment]
Hab es jetzt erst getestet, sorry - funktioniert bei mir ehrlich gesagt immer noch nicht
mein code dieses mal war:
` mform->addCustomLinkField(8, array('label'=>'Bild', 'class'=>'bereich1_bild', 'data-tel'=>'disable', 'data-mailto'=>'disable', 'data-formlink'=>'disable', 'data-intern'=>'disable'));
`

mit `	$mform->addTextAreaField(9, array('label'=>'Text', 'value'=>'REX_VALUE[9]', 'class'=>'bereich1_text'));
` oder den anderen Funktionen funktioniert es, nur bei CustomLinkField nicht

**Comment by joachimdoerr** [comment]
Der CustomLink ist ein sehr spezielles Element, da müsste man mal schauen wie das möglich ist.

**Comment by darwin26** [comment]
HI...
auch bei den addTab funktioniert die Übergabe der Attribute leider nicht.
`$MForm->addTab(" Bereich", array('data-foo'=>'blubb'));`

an die <li> der Tabs wird nichts geliefert.
MForm 5.2.2

hab mich auch an die defaults gewagt und in der mform_tabnavli.ini folgendes eingefügt:
`<li role="presentation" class="<element:class/>" <element:attributes/>>`

leider zeigt <element:attributes/> keine wirkung... trotz re-install mform und default theme nochmal speichern...

generell geht es mir "lediglich" um eine ID für die <li> der Tabs... diese fehlt.
und via
`$("#tabs ul.nav-tabs > li").each(function (i) {
            $(this).attr("id", i+1 );
        });`
find ich s nicht so schön (im Modul) ;)

Danke

**Comment by joachimdoerr** [comment]
Auch die Tabs sind sehr speziell. Und hier ist auch die Frage wohin mit den Attributen in die Nav-Li oder in den Content-Div.

**Comment by fietstouring** [comment]
Es wär super wenn man das in die Doku einfließen lassen könnte, dass man das zb so
`$mform->addCustomlinkField(1,array('label' => 'Link'));
$mform->addAttribute('data-media', 'disable');`

notieren muss, um Linktypen zu deaktivieren. Das musste ich erst hier recherchieren.  Hatte es mit 0 und 1 probiert, aber das geht nicht.

**Comment by joachimdoerr** [comment]
32d95a186ecd47ed8923d6da25d44ba90a6a2cff
