### ISSUE TITLE
Select <optgroup>

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/mform#124]
Es wäre sehr praktisch, wenn die Select-Elemente in Optgroups unterteilt werden könnten.

**Comment by joachimdoerr** [comment]
können sie.

**Comment by joachimdoerr** [comment]
Hier mal ein Beispiel aus einem meiner Entwicklungsmodulen: 

```
$mform->addMultiSelectField(3, array('1af'=>'test-1','2af'=>'test-2','3af'=>'test-3','4af'=>'test-4'), array('label'=>'Select optgroup'));
$mform->addMultiSelectField("5", array('group 1'=>array(1=>'test-1',2=>'test-2'), 'group 2'=>array(3=>'test-3',4=>'test-4')), array('label'=>'Select optgroup'));
```

**Comment by joachimdoerr** [comment]
Das Thema müsste in der Doku behandelt werden.

**Comment by joachimdoerr** [comment]
Es gibt ein Beispiel: https://github.com/FriendsOfREDAXO/mform/blob/master/pages/examples/base2_select.ini#L22
