### ISSUE TITLE
Formatierungsfehler

### ISSUE THREAD

**Issue by nilsology** [FriendsOfREDAXO/mform#127]
Wenn ich ein Formular erstelle bekomme ich immer folgende Darstellung. Egal ob mit MBlock oder nur MForm ... gibt es dafür einen Fix? Es scheint als fehle ein clearfix nach den Formgroups?

<img width="784" alt="screen shot 2017-10-09 at 13 24 24" src="https://user-images.githubusercontent.com/3009903/31336022-4a7491d8-acf5-11e7-9a9e-1a9063a36c92.png">

**Comment by skerbis** [comment]
Was ist das da für ein Symbol bei Überschrift?

**Comment by skerbis** [comment]
Hier schießt bei dir irgend ein CSS eines anderen AddOns dazwischen.

**Comment by nilsology** [comment]
Ahh, das ist eigentlich nur mein Lastpass, das Problem wie oben beschrieben, tritt aber auch auf, wenn Lastpass nicht aktiv ist.

**Comment by skerbis** [comment]
@nilsology Ich kann das nicht reproduzieren. Kannst du mal deinen Modul-Code posten?

**Comment by nilsology** [comment]
<?php

$id = 1;
$catId = 6;

$form = new MForm();

$form->addTextField("$id.0.title", ['label' => 'Überschrift']);
$form->addMediaField(1, ['label' => 'Faktencheck'], $catId);
$form->addMediaField(2, ['label' => 'Mittleres Bild'], $catId);
$form->addMediaField(3, ['label' => 'Bonus-Banner'], $catId);
$form->addTextField("$id.0.description", ['label' => 'Bonus-Text']);
$form->addTextField("$id.0.linkUrl", ['label' => 'Bonus-Link Url']);
$form->addTextField("$id.0.linkText", ['label' => 'Bonus-Link Ankertext']);

echo MBlock::show($id, $form->show());

**Comment by DanielWeitenauer** [comment]
Damit das Mform-Layout richtig sitzt, musst du am Anfang ein addFieldset() einfügen, da sonst eine entscheidende Bootstrap-CSS-Klasse fehlt.

**Comment by DanielWeitenauer** [comment]
Welche MForm Version nutzt du? Bei älteren Versionen musst du noch ein addFieldset() einfügen, da sonst eine CSS-Klasse für das Bootstrap-Layout nicht gesetzt wird.

**Comment by skerbis** [comment]
Korrekt ganz am Anfang ein Fieldset oder Tab , dann wird's hübsch. Aber Deine Darstellung erhalte ich nicht. Ich habe nur den Effekt, dass der erste Input die Buttons überlappt. 
So sieht es bei mir mit Fieldset aus
![bildschirmfoto 2017-10-09 um 17 32 44](https://user-images.githubusercontent.com/791247/31346659-1a861ee0-ad1a-11e7-992d-9f4c3a93ef9a.png)

**Comment by nilsology** [comment]
Danke, das probiere ich mal :) Habe die aktuelle MForm installiert.

**Comment by joachimdoerr** [comment]
Das problem ist wohl individuell - ich kann jedenfalls nichts dergleichen nachstellen deswegen close.

**Comment by nilsology** [comment]
Upps, es war in der Tat immer das Fieldset, das gefehlt hatte. +1
