### ISSUE TITLE
TabsTroubles

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/mform#129]
Anscheinend sind im letzten Release Tabs dazugekommen. Die ID des zuletzt geöffneten Tabs wird im [localstorage gespeichert](https://github.com/FriendsOfREDAXO/mform/blob/master/assets/mform.js#L32).

Mein Brot- und Buttermodul (Inhalt in 1 bis 4 Spalten) arbeitet mit verborgenen Tabs (selbstgestrickt, Bootstrap aber nicht mform). Beim Hinzufügen eines neuen Slices mit diesem Modultyp ist nur Spalte 1 / Tab 1 sichtbar, die anderen Spalten / Tabs sind verborgen:

![01](https://user-images.githubusercontent.com/7223820/32753802-8b488800-c8ce-11e7-8734-a5eb09f8a1be.png)

Der Redakteur kann im Reiter Einstellung ein Spaltenlayout wählen, danach stehen bis zu 4 Spalten / Tabs zur Verfügung:

![02](https://user-images.githubusercontent.com/7223820/32753872-e029e238-c8ce-11e7-91e7-563046971c78.png)

Hat ein Redakteur in einem existierenden Slice als letztes Spalte 2 / Tab 2 bearbeitet, merkt sich das mform im localstorage. Fügt der Redakteur nun ein neues Modul hinzu, versucht mform den zweiten Tab zu aktivieren, da ID/href der Tabs innerhalb dieses Modultyps gleich sind. Das funktioniert nur zur Hälfte - es wird der Tab von Spalte 1 und das Pane von Spalte 2 angezeigt.

![03](https://user-images.githubusercontent.com/7223820/32754839-cdc5a9a2-c8d2-11e7-94fe-f592d25cf4bf.png)

Was dann dazu führt, das die Inhalte für die erste Spalte eines einspaltigen Slices im Datenbankfeld der zweiten Spalte landen...

Ich lösche nun beim Seitenaufruf den localstorage Eintrag, damits läufts erstmal wieder. Auf die Schnelle hab ichs grade nicht geschafft, über die mform Methoden `addTab` und `closeTab` Tabs aufzumachen, um zu prüfen, wie mform die Taberstellung handhabt. Meine Frage daher: vergibt mform pro Tab eine eindeutige ID, die den localstorage Eintrag an genau einen Slice bindet? Wenn nicht, schlage ich eine Überarbeitung der Speichermethode für den zuletzt aktiven Tab vor.

**Comment by joachimdoerr** [comment]
MForm kann tabs auch nach rechts rücken und auch mit Icons versehen, es gibt kein Grund die Tabs selbst zu stricken.

**Comment by IngoWinter** [comment]
Mag sein, aber die Tabs hab ich mir gestrickt, als MForm das noch nicht konnte - ich mags auch gerade nicht umbauen :)
Zudem bin ich mir ziemlich sicher, dass mein Problem nicht durch MForm eigene Tabs gelöst wäre - mein Problem sind die versteckten Tabs. MForm identifiziert die Tabs anhand ihres hrefs. Beim gleichen Modultyp wäre imho auch bei MForm Tabs der href gleich - gleiches Problem. 
MForm merkt sich den Tab von Modul A, der aber bei Modul B verborgen ist. Öffne ich nun Modul B, versucht MForm den verborgenen Tab zu öffnen und puff.

**Comment by joachimdoerr** [comment]
Die frage ist ob man für die Tabs die history entfernt und ob man die Tabs Slice ID abhängig mach.
Ich denke Slice-ID abhängig wäre sinnvoll.

**Comment by IngoWinter** [comment]
Die Tabs an den Slice zu binden ist auf jeden Fall sinnvoll. Für eine History könntest du ein Objekt mform_slice_history im localstorage speichern, in dem als key die Slice-Id und als value die zuletzt geklickte Tab-Id drinsteht. Sowas in der Art hatte ich mal für obenstehendes Modul angedacht, habs dann aber wieder verworfen - zuviel Aufriss für zuwenig Nutzen...

**Comment by joachimdoerr** [comment]
Gibt es jemand der Lust hat das zu übernehmen?

**Comment by joachimdoerr** [comment]
Kann man machen aber dann muss ja wieder ich ran. Ich wäre froh wenn sich jemand darum kümmern könnte das ist ja keine große Sache. Etwas mehr mithilfe wäre super.

**Comment by skerbis** [comment]
@IngoWinter mach's mal raus … ich teste gerne :-)

**Comment by joachimdoerr** [comment]
@IngoWinter thanks !
