### ISSUE TITLE
CustomLink nicht kompatibel mit MBlock

### ISSUE THREAD

**Issue by nilsology** [FriendsOfREDAXO/mform#130]
Wenn ich ein CustomLink Feld in einem MBlock einbinde, dann "springe" ich bei Klick auf eine der 3 Link Möglichkeiten, wo normalerweise (wenn normal eingebunden) sich das jeweilige Popup öffnet, nur ganz nach oben.

**Comment by nilsology** [comment]
```php
<?php
$id = 1;
$mform = new MForm();
$mform->addFieldset('"Kästle"');
$mform->addTextField("$id.0.title", array('label'=>'Überschrift')); // use string for x.0 json values
$mform->addCustomLinkField("$id.0.link", array('label'=>'Seite'));
echo MBlock::show($id, $mform->show());
```

**Comment by joachimdoerr** [comment]
Custom Link läuft unter MBlock nur mit numerischer ID also `$mform->addCustomLinkField("$id.0.1", array('label'=>'Seite'));`
