### ISSUE TITLE
YFORM_TABLE-Widgets

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/mform#131]
Wie lassen sich diese in MForm verwenden?

**Comment by olien** [comment]
Oh.. Die hätte ich auch gerne in mForm!!!!!

**Comment by IngoWinter** [comment]
schon probiert die einfach als html zu setzen?

**Comment by skerbis** [comment]
👍 @IngoWinter  das ist der richtige Weg.

**Comment by alexplusde** [comment]
Ich habe das Issue wieder aufgemacht, weil es zwar eine Antwort gibt, aber die konkrete Lösung aussteht und auch nicht in den Docs zu finden ist.

**Comment by skerbis** [comment]
ok, war mir nicht bewusst.

**Comment by joachimdoerr** [comment]
Bitte Custom-Link YLink option verwenden.
