### ISSUE TITLE
customLink Link-Typ in der Ausgabe

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mform#132]
Wäre cool wenn man in der Ausgabe abfragen könnte welcher Link-Typ in der Eingabe gesetzt wurde. Weiss gerade nicht wie man das am besten übergeben könnte aber evtl. als Teil des Values?

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/blob/master/lib/classes/Utils/MFormOutputHelper.php#L30-L65

**Comment by ynamite** [comment]
@joachimdoerr oh danke! Was übergibt man der Funktion? Einfach die Ausgabe des customLinks?

**Comment by ynamite** [comment]
Passt, danke tausend!
