### ISSUE TITLE
Parameter 'types' akzeptiert im Array keine Leerzeichen nach Komma

### ISSUE THREAD

**Issue by medienfeuer** [FriendsOfREDAXO/mform#133]
Funktioniert nicht:
`$mform->addMedialistField(1, array('types'=>'pdf, doc, docx, xls, xlsx', 'preview'=>0, 'category'=>55, 'label'=>'Dateien'));`

Funktioniert:
`$mform->addMedialistField(1, array('types'=>'pdf,doc,docx,xls,xlsx', 'preview'=>0, 'category'=>55, 'label'=>'Dateien'));`

**Comment by joachimdoerr** [comment]
ja das wird direkt an die widget classe weiter gereicht, man könnte die Leerschläge zuvor replacen.

**Comment by joachimdoerr** [comment]
12d5df64d40dd54ac27b10b9e8bbbe2d70860d26
