### ISSUE TITLE
Css/jss nur laden wenn nötig

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/mform#134]
Wäre es möglich die ganzen css/js includes nur dann zu laden, wenn auch ein mform in der aktuellen seite enthalten ist?

Aktuell lädt man hier viel zeug und braucht es oft nicht....

Triggered by https://github.com/redaxo/redaxo/issues/1406

**Comment by staabm** [comment]
D.h. Ein PR der nur im slice edit die js/css dateien lädt ist erwünscht?

**Comment by joachimdoerr** [comment]
@staabm ja sehr gerne ist ein PR erwünscht!
