### ISSUE TITLE
Warnings im backend

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mform#135]
Warning: sizeof() [function.sizeof]: Parameter must be an array or an object that implements Countable in /Users/aaa/Sites/abc/redaxo/src/addons/mform/lib/classes/MFormElements.php on line 71
Warning: sizeof() [function.sizeof]: Parameter must be an array or an object that implements Countable in /Users/aaa/Sites/abc/redaxo/src/addons/mform/lib/classes/MFormElements.php on line 68

**Comment by joachimdoerr** [comment]
Kannst du bitte noch den Modul input dazu Bereitstellen.

**Comment by olien** [comment]
oh. man. meinst du das liegt an mir????? :-)
der input ist zu heftig als dass du dir den angucken möchtest.
der fehler kam jetzt mit dem redaxo update auf die beta

**Comment by joachimdoerr** [comment]
ok, welche Elemente hat du im Einsatz? also in deinem Modul zu welchem die warnings fliegen.

**Comment by olien** [comment]
Quasi alle :-(

**Comment by joachimdoerr** [comment]
sehr hilfreich :D

**Comment by olien** [comment]
Ich weiß. Sorry... ist das eierlegendewollmilchsaumodul. da ist halt nahezu alles drin... ich versuche das heute abend mal aufzudröseln

**Comment by joachimdoerr** [comment]
jo ich schaue auch erstmal ob es ein generelles problem ist komme nur jetzt nicht dazu

**Comment by olien** [comment]
Mit PHP 7.1.12 sind die Warnings Fehler weg... (anstelle von PHP 7.2.1)

**Comment by joachimdoerr** [comment]
Das ist gut zu wissen Danke!

**Comment by domenikhofer** [comment]
Ich erhalte mit PHP 7.2 die gleichen Fehlermeldungen. Kann aber nicht auf 7.1 umstellen.

Bsp:

Input
`<?php 
$mform = new MForm();
$mform->addMedialistField(1,array('preview'=>1),1,array('label'=>'Bilder'));
$mform->addTextField(1, array('label'=>'Mood Title'));


$mform->addMediaField(1,array('preview'=>1),1,array('label'=>'Logo'));
$mform->addCheckboxField(2, array(1=>'Anzeigen'), array('label'=>'Header-Navi'));
echo $mform->show();
?>`

Output
`<?php 
$imgs = explode(',', "REX_MEDIALIST[1]");
$title = ("REX_VALUE[1]");
$text = ("REX_VALUE[2]");

?>

<section class="blockGallery">			
				<div class="imgWrapper">
				<div class="intro">
				<div class="introContent">
				<div class="text">
				<h3 class="beige"><?php echo $title ?></h3>
				<p><?php echo $text ?></p>
				</div>
				</div>
				</div>
				</div>
				<?php 
    foreach($imgs as $img){
        echo '<div class="imgWrapper"><a href="/media/'.$img.'" class="lazyload" data-fancybox="images" data-src="/media/'.$img.'" ></a></div>';
    }
    ?>
				<div class="imgWrapper invisible"><a></a></div>
				<div class="imgWrapper invisible"><a></a></div>
				<div class="imgWrapper invisible"><a></a></div>
				</section>



`

**Comment by joachimdoerr** [comment]
@domenikhofer bitte die neuste git master verwenden, damit kommt das problem dann nicht mehr vor. Release kommt auch bald.

**Comment by alexplusde** [comment]
Release wäre super :)

**Comment by joachimdoerr** [comment]
Das ist gar nich so einfach da jeglicher redactor support rausgeflogen ist, der sollte aber erst für das main release komplett fliegen.

**Comment by alexplusde** [comment]
Warum ist denn der Redactor-Support rausgeflogen und soll er das? Kann man MForm dann nicht mehr damit benutzen? Jedenfalls würden wir einige Websites gerne umstellen auf PHP 7.2 und bekommen dann eben solche Fehlermeldungen im Backend.

**Comment by alexplusde** [comment]
Oder kann man vlt. einen Hotfix-Release machen?

**Comment by skerbis** [comment]
@alexplusde ab der nächsten Version müssen die Editoren die nötige Unterstützung mitliefern. Im CKE5 ist dies bereits geschehen, die anderen AddOn-Entwickler sind informiert.

**Comment by olien** [comment]
Ist dann aktuell nur der CKE5 nutzbar???

**Comment by skerbis** [comment]
im hier vorliegenden GitHub-Stand - ja. @olien

**Comment by olien** [comment]
hm. Schade... 
Ist der sonst abwärtskompatibel?

**Comment by joachimdoerr** [comment]
sorry hab MBlock mal wieder mit MForm verwechselt natürlich läuft Redactor wie jeder andere Editor mit MForm ohne Probleme.

**Comment by skerbis** [comment]
@joachimdoerr bin auch drauf reingefallen …. grr

**Comment by alexplusde** [comment]
Ich war jetzt einfach so frech und habe eine inoffizielle 5.1.1-Version in den Installer geladen, die nur diese Änderung enthält, weil wir jetzt einige Projekte haben, in denen wir auf PHP 7.2 umgestellt haben und vergessen hatten, mform zu aktualisieren. 

Ich denke, auch andere werden es danken und ja, ich verspreche, dass ich sowas nie wieder mache ;)

**Comment by skerbis** [comment]
Ich habe das Release offline gestellt @alexplusde
https://github.com/FriendsOfREDAXO/mform/issues/142

**Comment by joachimdoerr** [comment]
@alexplusde sehr gut. Ich schaumal ob ein neuer release sinnvoll ist.
