### ISSUE TITLE
addDescription HTML broken 

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/mform#140]
Wenn ich addDescription benutze, ist das HTML nicht korrekt, die paddings stimmen nicht:
![image](https://user-images.githubusercontent.com/688274/43646697-df4efea8-9735-11e8-8b0f-70d90e8948e5.png)

**Comment by joachimdoerr** [comment]
Hier fehlt einfach nur ein CSS Style das war wohl schon immer so - bitte gerne ein hübschen CSS Style bauen und als Pull request mit einfließen lassen.

**Comment by DanielWeitenauer** [comment]
Hier ist nicht zwingend ein Style nötig. Die Ausgabe müsste lediglich in einen Tag eingebunden werden. Z.B. `<p class="col-sm-offset-2 col-sm-10 small">Text</p>`

**Comment by joachimdoerr** [comment]
@DanielWeitenauer ja dann sollte es aber `addHtml` sein nicht `addDescription` ich denke für die Description sollte man schon ein Style haben.

**Comment by skerbis** [comment]
done
