### ISSUE TITLE
aktuelle Installer Version enthält nicht alle Dateien

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mform#142]
Die aktuelle Version im Installer scheint nicht komplett zu sein. Zum Beispiel fehlt im Ordner Utils die Datei für die Klasse MFormOutputHelper.

Ich glaube das war auch in der Version zuvor der Fall. 

Ist das evtl. gewollt?

EDIT: hatte gerade von 5.1.0 (glaube ich) auf 5.1.1 aktualisiert fyi

**Comment by skerbis** [comment]
Der Verursacher ist informiert

**Comment by alexplusde** [comment]
War mein Fehler. 5.1.1 ist erst mal wieder offline und ich schaue, warum das nicht geklappt hat. 5.1.0 ist exakt gleich bis auf den PHP7.2-fix, also kannst du problemlos downgraden. Bei mir hat das Update jedoch 4x geklappt.

Danke fürs melden!

**Comment by alexplusde** [comment]
> Ich glaube das war auch in der Version zuvor der Fall.

Heißt aber eigentlich, dass die 5.1.1 im Vergleich zur 5.1.0 keine neuen Fehler gebracht hat.

**Comment by skerbis** [comment]
Ist nicht Teil des releases. Kannst Sie aber schon nutzen indem du sie dazu kopierst. Kommt mit dem nächsten Haupt-Release. Alternativ verwende die aktuelle Github-Version.
