### ISSUE TITLE
CustomLinkFields mit Strings in der ID

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/mform#143]
Hi, ich bin gerade ebenfalls über #130 gestolpert. 
Wäre super, wenn es auch möglich wäre, auch Strings in der ID des Feldes anzugeben. 
Leider werde ich aus dem Code des Generators nicht wirklich schlau, sonst hätte ich mich daran versucht.

**Comment by joachimdoerr** [comment]
Leider ist das nicht so einfach in MBlock wird für das Custom-Link Element das Link-Widget als Basis genutzt, das führt dann zu diversen Problemen wenn im Name-Tag ein String enthalten ist.

**Comment by joachimdoerr** [comment]
Das ist richtig mühselig das aufzubohren ich denke mit einem numerischen Name-Tag kann man leben.

**Comment by DanielWeitenauer** [comment]
Es sollte noch in die Doku aufgenommen werden.
