### ISSUE TITLE
jquery-pjax schmiert ab bei der Modul-Eingabe, mform Version 5.2.0

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mform#144]
mit mform Version 5.2.0 schmiert jquery-pjax ab, wenn man ein Modul versucht zu editieren, wo eine medialist oder ein media Feld hinterlegt ist.

Resultierendes HTML in der Modul-Eingabe:
```<div class="col-sm-10"><html><body><div class="rex-js-widget rex-js-widget-medialist rex-js-widget-preview rex-js-widget-preview-media-manager">...```

Vermutlich hängt sich pjax wegen des zusätzlichen HTML-/BODY-Tags auf

**Comment by joachimdoerr** [comment]
6bb609a964921514709c97a2ced285d0d695afeb

**Comment by joachimdoerr** [comment]
5.2.1 release ist im installer
