### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mform#145]
Hi,

nach dem Update bekomme ich folgende Warnings (ne Menge davon)

> Warning: sizeof() [function.sizeof]: Parameter must be an array or an object that implements Countable in /Users/abx/Sites/hallo/redaxo/src/addons/mform/lib/classes/MFormElements.php on line 71

REDAXO 5.6.2
PHP 7.2.7 

LG
Oliver

**Comment by dunnodun** [comment]
Das Problem wurde in 5.1.1 behoben, jedoch ist es anscheinend in 5.2.1 wieder hinzugekommen. Mir werden auf Version 5.2.1 auch gar keine Inputfelder mehr angezeigt sondern nur die Fehlermeldung.

**Comment by skerbis** [comment]
5.1.1???? wo ist die? Bitte die Lösung als PR einreichen. Die 5.1.1 wurde nicht aus GitHub veröffentlicht.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/c36979ab51ba91d36a42b2de8d7d70ec0f95424d

**Comment by skerbis** [comment]
Release kommt heute
