### ISSUE TITLE
Übergabe des Linktyps beim customLinkField

### ISSUE THREAD

**Issue by tema-web** [FriendsOfREDAXO/mform#148]
Das customLinkField ist klasse, um viele Input-Felder zu vermeiden. Allerdings speichert es nur den Wert des Feldes in der Datenbank (Bei intern die ID des Artikels, bei Medienpool den Dateinamen etc.) 
Wäre es möglich, direkt ein Json-Array zu speichern, bei dem zusätzlich gespeichert wird, was ausgewählt wurde (Intern, Media ...)? Die Erstellung des Links ohne diese Info bekomme ich leider nicht sicher hin.

**Comment by joachimdoerr** [comment]
Es wäre schon sinnvoll eine solche Methode in MForm bereit zu stellen.

**Comment by tema-web** [comment]
Ja, denke ich auch. Thomas Lösung funktioniert auch nicht ganz sicher.  is_numeric würde bei Artikel-Id und Tel-Nummern true liefern. Und wenn FILTER_VALIDATE_URL false liefert kann trotzdem eine externe URL übergeben worden sein, bei der kein http(s):// dabei ist.

**Comment by skerbis** [comment]
@tema-web das ist nur ein kurzes Beispiel. Ist entstanden bevor tel. und mail dazu gekommen sind. Telefonnummern sind übrigens korrekt geschrieben nicht numerisch

**Comment by tema-web** [comment]
@skerbis ja, aber ich traue den Redakteuren nicht ;-)

**Comment by skerbis** [comment]
Gut, dann brauchst du ne Validierung direkt im Widget. Wie oben beschrieben, wird das Widget unterschiedlich verwendet. Ich nutze es ja z.B. um URLs der Videodienste zu erkennen, andere für wiederum andere Zwecke z.b. individuelle Aufrufe zu erzeugen. Eine Hilfsmethode wie diese ist halt eine Möglichkeit es severseitig zu erkennen und zu verarbeiten. Der Typ müsste aber per JS validiert werden, denke ich.

**Comment by tema-web** [comment]
Eine Validierung direkt im Widget geht in meinen Augen zu weit. Ich denke, es würde ausreichen, wenn das Widget den Typ des Links mit übergibt (das "weiß" das Widget ja durch den Klick auf den entsprechenden Button). Was dann wie validiert wird kann/sollte jeder bei der Ausgabe selber einstellen können. Aber so weiß man zumindest, was da ankommen sollte, um es dann entsprechend validieren zu können.

**Comment by tema-web** [comment]
Jo, das war meine Idee. Zwei REX_VALUES finde ich auch zu problematisch. Wenn ein JSON-String gespeichert wird geht allerdings die Abwärtskompatibilität flöten. Auch nicht unbedingt schön :-(

**Comment by skerbis** [comment]
Bitte optional als mode

**Comment by joachimdoerr** [comment]
Ich würde das eher nicht machen wollen. Gerne als PM sonst close.

**Comment by joachimdoerr** [comment]
Kein Feedback, keiner will es machen -> close.
