### ISSUE TITLE
Input type number

### ISSUE THREAD

**Issue by thorol** [FriendsOfREDAXO/mform#149]
Es nicht möglich ein Input-Feld vom Type "number" zu erzeugen.
yform Version 2.2
Evtl. ist dies im Version 3 Verfügbar?

`$mform->addInputField( "number","$id.0.hr_size", array( 'label' => 'Stärke') );`

**Comment by skerbis** [comment]
@thorol Sollte in der aktuellen Version funktionieren.

**Comment by skerbis** [comment]
getest, funktioniert
