### ISSUE TITLE
BUG: Tabs defekt

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/mform#151]
In der aktuellen Version werden immer neue Tab Groups aufgemacht statt Tabs nebeneinander anzulegen.

![tabterror](https://user-images.githubusercontent.com/7023022/47345850-13d14180-d6ac-11e8-9c57-54b2eee13df8.PNG)

Code:
```
// init mform
$mform = new MForm();

$mform->addTab('Angebots-Übersicht');
$mform->closeTab();

$mform->addTab('Detail-Ausgabe');
$mform->closeTab();

// parse form
echo $mform->show();
````

**Comment by joachimdoerr** [comment]
Quickfix: 
`// init mform
$mform = new MForm();

$mform->addTab('Angebots-Übersicht');

$mform->addTab('Detail-Ausgabe');
$mform->closeTab();

// parse form
echo $mform->show();`

**Comment by elpschulzo** [comment]
Hilft in meinem Fall nicht und ändert nichts @joachimdoerr :(

**Comment by joachimdoerr** [comment]
Bitte mit der neusten Master testen: https://github.com/FriendsOfREDAXO/mform/commit/c4237ebbeff9227cb099bfd415b9f1233b8c3bf0

**Comment by elpschulzo** [comment]
Wenn man Fieldsets im Tab hat und *nicht* das letzte Fieldset schließt, dann klappt es, schließt man es, wird wieder eine neue Tabbar aufgemacht. Ob das bei anderen Strukturelementen auch so ist, ungetestet.

Ich habe ein Setting mit 2 Tags und jeweils mehreren Fieldsets drin. Damit zerschießt es das gesamte Layout dann komplett (schlimmer als vorher). --> Screen als PN

**Comment by joachimdoerr** [comment]
So bitte nochmal mit der neusten Master versuchen. Nun sollte das ganze korrekt laufen.

**Comment by joachimdoerr** [comment]
läuft auch damit nicht wirklich, die gesamte Lösung lässt sich schwer anpacken ohne generell das handling mit diesen Gruppen Elementen zu verändern. Die aktuelle Master ist momentan gebrochen, deswegen.

**Comment by skerbis** [comment]
getestet 👍
