### ISSUE TITLE
checkbox generiert label doppelt, erstes ist leer

### ISSUE THREAD

**Issue by shaack** [FriendsOfREDAXO/mform#152]
Eine checkbox enthält selbst das label, aber das label aus `mform_deafult.ini` wird auch generiert.
Das führt in horizontalem layout dazu, dass ein Leerraum über der checkbox entsteht.
```
<div class="form-group">
    <label for="rv3_2"></label>
    <div class="checkbox"><label class="description" for="rv3_2"><input id="rv3_2" type="checkbox" name="REX_INPUT_VALUE[2]" value="label" checked="checked" data-parsley-multiple="REX_INPUT_VALUE2" data-com.agilebits.onepassword.user-edited="yes"> Link "Ältere anzeigen"</label></div>
</div>
```
Einfacher Workaround war, das leere label per css im `theme.css` zu verstecken.
```
.mform label:empty {
    display: none;
}
```

**Comment by skerbis** [comment]
Kann ich 6.0 nicht reproduzieren. Daher close
