### ISSUE TITLE
CUSTOM_LINK Value erst bei Auswahl austauschen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mform#154]
Das Value wird direkt bei Click auf die Picker entfernt. 
Wenn man sich entscheidet doch keinen anderen Link zu wählen, muss man den alten händisch wiederherstellen. Ist unschön, falls man in dem Block schon weitere Änderungen durchgeführt hat und so nicht abbrechen kann.

**Comment by joachimdoerr** [comment]
Das Problem trutt nur bei klick auf den Media-Button auf.

**Comment by skerbis** [comment]
Stimmt

**Comment by skerbis** [comment]
Ist aber dennoch ärgerlich

**Comment by joachimdoerr** [comment]
@skerbis das wird nichts, weil redaxo mit diesen behämmerten popups arbeitet muss ich leider die Formulare vor dem öffnen der popups für die popups vorbereiten. und da sich link und media widgets grundlegend unterscheiden kann ich da auch nichts am Prozedere ändern. Sorry.

**Comment by skerbis** [comment]
Ok

**Comment by joachimdoerr** [comment]
60db99689487f1132c8d6eb1f4c769b054cc0b2b
