### ISSUE TITLE
Dokumentation für Ausgabe von mform / mform-Blocks

### ISSUE THREAD

**Issue by xamiam** [FriendsOfREDAXO/mform#155]
Als Redaxo-Neuling habe ich trotz langer Recherche immer noch nicht rausgefunden, wie ich die mform-Eingaben im Modul auslesen / ausgeben kann. 
Es wäre toll (und sicherlich nicht besonders aufwendig), die Dokumentation entsprechend mit einem kurzen Snippet zu erweitern. Danke für Eure tolle Arbeit!

**Comment by joachimdoerr** [comment]
Hello @xamiam, 
du kannst die Eingaben der MForm Modul-Formulare einfach mit dem "Redaxo-Standard" auslesen: `REX_VALUE[id=x]`. Siehe: https://redaxo.org/doku/master/redaxo-variablen
lg
Joachim

**Comment by skerbis** [comment]
Beispiele findest du auch in der Modulsammlung https://github.com/FriendsOfREDAXO/Modulsammlung/tree/master/lib/module_mform_mblock
