### ISSUE TITLE
Übersetzung im Table Manager fehlt noch

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/mform#159]
Zur Zeit steht noch im Table Manager:
![Bildschirmfoto 2019-03-15 um 16 16 26](https://user-images.githubusercontent.com/45007596/54441775-b8c4e780-473d-11e9-8d14-168f494253ee.png)
> [translate:yform_values_imagelist_description]

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/mform/pull/160 danke
