### ISSUE TITLE
CustomLink: Konfiguration der Buttons greift nicht mehr 

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/mform#161]
das custom link feld lässt in einem aktuellen projekt (REX 5.7, MForm + YForm aktuell) in einem mform modul nicht mehr anpassen. d.h. alle buttons werden angezeigt:

`$mform->addCustomLinkField("1", array('label'=>'Video', 'data-tel'=>'disable', 'data-mailto'=>'disable', 'data-formlink'=>'disable', 'data-intern'=>'disable'));`

hat sich hier die notation geändert?

ps: ich habe das feld im gleichen projekt in einer yform tabelle im einsatz: da funktioniert es wie gewollt

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/828a9d94ac3d58720941492dc3bc3242e3624ad9
