### ISSUE TITLE
CUSTOM_LINK fuktioniert nicht in tieferen Array-Ebenen

### ISSUE THREAD

**Issue by tema-web** [FriendsOfREDAXO/mform#162]
Habe folgendes Problem festgestellt:
`$mform->addCustomLinkField("$n.myvar.link", $attributes);` funktioniert einwandfrei,
`$mform->addCustomLinkField("$n.myvar.myvar2.link", $attributes);` hingegen nicht. Dann steht im Value des Inputfeldes 'Array'.

**Comment by joachimdoerr** [comment]
Das Problem wurde behoben: https://github.com/FriendsOfREDAXO/mform/issues/164
