### ISSUE TITLE
Customlink in YFORM/Table Manager -> externer Link wird immer angezeigt

### ISSUE THREAD

**Issue by Geri2017** [FriendsOfREDAXO/mform#168]
Obwohl ich im Table Manager die Checkbox bei externer Link herausnehme, wird diese trotzdem in der Datentabelle angezeigt.

![Bildschirmfoto 2019-05-21 um 11 44 36](https://user-images.githubusercontent.com/45007596/58085991-12261880-7bbe-11e9-94c6-d248f346ce50.png)
![Bildschirmfoto 2019-05-21 um 11 44 56](https://user-images.githubusercontent.com/45007596/58086008-15b99f80-7bbe-11e9-8f35-8aa8408159e8.png)

**Comment by skerbis** [comment]
erledigt in 6.0
