### ISSUE TITLE
CustomLink: Assoziative Referenzierung fehlt!

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/mform#169]
Hallo Leute,

erstmal vielen Dank für das tolle CustomLink-Widget. Geniales Ding!
Aber kann es sein, dass das CustomLinkField in Verbindung mit mBlock aktuell nur numerische Array-Schlüssel unterstützt? Ich hatte "funktionierenden Code" ohne CustomLink (Muster siehe unten) und wollte da mal fix das CustomlinkField hinzufügen. Also meinen Code getreu dem (korrekten) Schema erweitert - und Pustekuchen. Es hat nicht funktioniert, egal wie ich das Customlink-Field benutze, jeder Klick in das Widget verpufft wirkungslos.

Ich habe es dann einmal mit numerischen statt assoziativen Key probiert und ZACK - schon läuft das... Jetzt wo ich das weiß ist es kein Problem, aber ein Bugfix wäre denke ich sinnvoll um anderen Usern die Fehlersuche zu ersparen...

Textfeld
```### INPUT
$form->addTextField("$id.0.mein_textfeld"); ### FUNKTIONIERT
$form->setAttributes(array(
	'label'=>'Mein Textfeld'
));
### OUTPUT
$array = (array)rex_var::toArray('REX_VALUE[1]');
foreach($array as $element){
	$value = (string)$element['mein_textfeld']; ### FUNKTIONIERT
}
```
CustomLink
```### INPUT
$form->addCustomlinkField("$id.0.mein_linkfeld"); # => FUNKTIONIERT NICHT
$form->addCustomlinkField("$id.0.1"); # => FUNKTIONIERT
$form->setAttributes(array(
	'label'=>'Mein Linkfeld',
	'data-mailto' => 'disabled'
));
### OUTPUT
$array = (array)rex_var::toArray('REX_VALUE[1]');
foreach($array as $element){
	$value = (string)$element['mein_linkfeld']; ### FUNKTIONIERT NICHT
	$value = (string)$element['1']; ### FUNKTIONIERT
}
```

Gruß,
dpf-dd

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/issues/130

**Comment by dpf-dd** [comment]
Ui das Problem ist ja schon länger bekannt!? Ich dachte das CustomLink-Widget ist neu... lol

Da das alte Issue aber ohne weitere Berücksichtigung geclosed wurde nehme ich an, dass es bei der numerischen Referenzierung bleibt und hier keine "Lösung" angedacht ist?

**Comment by skerbis** [comment]
Doku ergänzt: https://github.com/FriendsOfREDAXO/mform/commit/f03d4ddbbf73d46e18ddd36aa31da851040c6c0d
