### ISSUE TITLE
Custom Link: Inkonsistenz beim Speichern

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/mform#170]
Das Feld speichert die Daten abhängig von seiner Verwendung unterschiedlich ab:

- bei der Verwendung in Mform werden die Daten in REX_VALUE gespeichert
- bei der Verwendung als HTML Variable REX_CUSTOM_LINK landen die Daten in REX_LINKLIST

Aus meiner Sicht ist es sinnvoll, den Speicher anzugleichen.

**Comment by joachimdoerr** [comment]
5a7b1914f33c1811d005b19b65ff02ea06b83a6f
