### ISSUE TITLE
imagelist YForm: verhindern das ein verwendetes Medium im Medienpool gelöscht wird

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/mform#175]
https://github.com/yakamara/yakme/issues/6#issue-461486843

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tricks/blob/master/_docs/addons/yform/protect_in_use_data.md
- Hier eine kleine Hilfe - Die Class dann um das gewünschte Feld erweitern.

**Comment by skerbis** [comment]
@isospin

**Comment by joachimdoerr** [comment]
Wie soll das MForm Widget das gewährleisten?

**Comment by skerbis** [comment]
mform müsste die Prüfung für YFORM Tabellen mitliefern

**Comment by skerbis** [comment]
https://github.com/yakamara/yakme/blob/3638ea77db3c4ab4bcf52e5cb242c1dc6ab4c505/lib/Yakme/Extension/YForm.php#L78

**Comment by skerbis** [comment]
- https://github.com/FriendsOfREDAXO/mform/commit/8f740ffcfbc817da5fbd4147c63fe1fb37f391f3
- https://github.com/FriendsOfREDAXO/mform/commit/726718da0943a4b2ff58fd9edd2f2a4296b74876

MFORM 6
