### ISSUE TITLE
Multiselect mit Value 0

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/mform#177]
Hey,

ich hatte eben einige Wechselwirkungen bei einem Multi Select, sobald eine Option mit dem Value 0 vorhanden war. Die Option wurde angewählt, obwohl beim vorherigen Bearbeiten die Option nicht ausgewählt wurde und landete dementsprechend fälschlicherweise in der DB. Kann das mit Default Settings zu tun haben?

Viele Grüße
Pascal

**Comment by joachimdoerr** [comment]
@pschuchmann kannst du bitte ein Beispiel Modul liefern. Danke!

**Comment by pschuchmann** [comment]
@joachimdoerr ich kriege es gerade nicht mehr reproduziert, zu lange her. Ich schließe es vorerst, falls es nochmal auftauchen sollte, schicke ich den Input direkt mit! Danke dir fürs Kümmern!
