### ISSUE TITLE
CustomLinkField: Keine Startkategorie für Medienpool-Auswahl möglich!

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/mform#182]
Leider kann ich einem mForm CustomLinkField keine Startkategorie des Mediapools mitteilen!
```
$field->addCustomLinkField('1', ['label'=>'Label', 'data-tel'=>'disable', 'data-mailto'=>'disable', 'data-formlink'=>'disable', 'data-intern'=>'disable']);
$field->setParameters([
    'types' => 'mp4', ### funktioniert
    'category' => 11 ### funktioniert nicht
    'setMediaCategoryId' => 11    ### funktioniert auch nicht
]);
```

Im Beispiel oben ist `category` die MForm-Schreibweise, während `setMediaCategoryId` die rex_form Schreibweise ist. Letztere funktioniert, wenn ich das CustomLinkField auch aus rex_form heraus benutze. Wenn ich es aber aus MForm heraus benutze, bekomme ich keine Startkategorie mitgegeben :(

**Comment by joachimdoerr** [comment]
4faafdec3bc0ffa7a45b84f6a3a499726b875e7d
