### ISSUE TITLE
Custom-Link Popup: vorhandene Daten übernehmen

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/mform#183]
Mit der Option 'Externe URL verlinken' können auch Ankerlinks (#...) eingegeben werden. Allerdings wird beim erneuten Aufruf das Feld mit dem Default (http://) überschrieben. 

Es wäre schön, wenn Anker erkannt und nicht überschrieben werden.

**Comment by DanielWeitenauer** [comment]
Sorry, Ankelinks funktionieren, allerdings werden vorhandene Einstellungen nicht übernommen. Beim Öffnen des Feldes wird dies stets mit dem jeweiligen Standard-Prefix vorbelegt. Das gilt für alle prompt()-Felder. Schön wäre, wenn ein vorhandener Eintrag übernommen würde, sofern sie vom Typ passt. Das würde z.B. das Beseitigen von Tippfehlern erleichetern.

**Comment by joachimdoerr** [comment]
e9765059b04c1cf904d6f07bc6d803d99a2e2762
