### ISSUE TITLE
CustomLinkField in MBlock funktioniert nicht

### ISSUE THREAD

**Issue by dundunn** [FriendsOfREDAXO/mform#184]
Wenn man ein CustomLinkField in MBlock hinzufügt, kann man dieses bei der Eingabe nicht verwenden. Das JS wird nicht ausgelöst, stattdessen wird per Ankerlink an den Anfang des Blockes gesprungen

**Comment by dpf-dd** [comment]
Das sind natürlich ziemlich wenige Infos die du da mitgibst.
Ich habe hier ein Redaxo 5.8.0 und da funktioniert das CustomLinkField ganz tadellos in einem MBlock!

`$form->addCustomLinkField("$mblock_id.0.1");`

**Comment by dundunn** [comment]
Ich habe einen nichtnumerischen Key verwendet. https://github.com/FriendsOfREDAXO/mform/blob/master/plugins/docs/docs/de_de/form_custom_link.md
