### ISSUE TITLE
default-value wird ignoriert (V 5.3.1)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mform#185]

**Comment by mbodon** [comment]
musst ich gerade auch feststellen und wollte gerade ein Issue anlegen ... aber dann sind wir hiermit schon zu zweit ;-)

**Comment by skerbis** [comment]
Codebeispiele bitte @olien @mbodon

**Comment by mbodon** [comment]
Hatte diesen Code mal probiert gehabt (war schon am 14.Mai) und leider wurde der Default-Wert nicht übergeben ...
<?php
$mform = new MForm();
$mform->addTextField(1, array(‘label’ => ‘Label Name’));
$mform->setDefaultValue(‘Default Value’);
echo $mform->show();
?>

**Comment by joachimdoerr** [comment]
Das Defaultvalue greift auch nur beim anlegen eines Moduls nicht beim editieren!

**Comment by joachimdoerr** [comment]
Nach Prüfung funktioniert der default-value korrekt: beim anlegen ist er da nach speichern nicht mehr sofern man empty oder etwas anderes eingegeben hat. Wichtig default value != placeholder!

**Comment by ynamite** [comment]
In Zusammenhang mit mblock funktioniert setDefaultValue allerdings nach wie vor nicht @joachimdoerr. Soll ich dazu bei mblock ein Issue anlegen?

**Comment by skerbis** [comment]
Hallo ynamite. Du meinst wenn du einen weiteren Block in mblock anlegst? In dem Fall ist's verständlich da mblock ja "nur" per JS das Formularfeld dupliziert.

**Comment by ynamite** [comment]
@skerbis nein ich meine beim initialen Block. Ich hab dort ein Select-Feld und wenn ich dort ein Default-Value angebe, passiert nix. Ausserhalb des Mblocks funktioniert's.

**Comment by skerbis** [comment]
Getestet: bitte als issue bei mblock anlegen @ynamite

**Comment by skerbis** [comment]
@ynamite https://github.com/FriendsOfREDAXO/mblock/issues/82
