### ISSUE TITLE
imagelist funktioniert nicht mehr richtig

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mform#193]
~~imagelist scheint nicht mehr richtig zu funktionieren.~~

~~in Mform:
eingefügte Bilder können nicht selektiert und somit auch nicht mehr gelöscht werden.~~

~~Mit yform 3.4:
Bei Klick auf "Medium auswählen" erhalte ich in der Konsole folgenden Fehler:
`TypeError: source is null`~~

Update: Offenbar gibt es Konflikte mit ui_tools Addon; war mir zwar mal bewusst, aber hatte ich nicht mehr präsent ... Schade das es keinen Hinweis gibt.

Jedenfalls bin ich etwas weiter, nun funktioniert die Imagelist zwar mit yform und mform, aber nicht mit mblock. Ist das bekannt?

**Comment by ynamite** [comment]
Offenbar ändert yform die IDs einiger imagelist Felder, was zu diesem Fehler führt.

Abgesehen davon funktioniert auch die Auswahl von Bilder in der imagelist zur Zeit nicht mehr, so kann man einmal eingefügte Bilder nicht mehr aus der imagelist löschen.

**Comment by ynamite** [comment]
Update: Imagelist funktioniert scheinbar auch ausserhalb von yform nicht richtig. Bilder können zwar sortiert werden, aber nicht mehr gelöscht bzw. ausgewählt werden

**Comment by skerbis** [comment]
> Offenbar gibt es Konflikte mit ui_tools Addon
Ja mit einer älteren Version. Mit der aktuellen sollte es kein Problem geben 

> aber nicht mit mblock
Auch das ist bekannt und kann aktuell nicht gelöst werden. Das gilt auch für viele andere custom Valiues wie z.B. aus YFORM.. 

Das Problem wird hier besprochen: https://github.com/redaxo/redaxo/issues/3694
