### ISSUE TITLE
Beta Version Mform -> Bilder mit addMediaField wirft js Fehler

### ISSUE THREAD

**Issue by CaptainMik** [FriendsOfREDAXO/mform#196]
Hi, ich habe gerade mal die Beta ausprobiert, Fehler tritt auf, wenn man das so benutzt:
$mform->addMediaField(2, array('label' => 'Bild'))

Wenn man das Bild übernehmen will kommt ein JS Fehler.

**Comment by joachimdoerr** [comment]
@CaptainMik  was für ein JS Fehler genau, welches System? IE, Edge, Safari, Firefox...

**Comment by CaptainMik** [comment]
Sorry habs schon wieder rausgeworfen, aber es war im Chrome und FF. Irgendsowas wie dass er ein leeres Value hat und deshalb das Bild nicht in das Bilderfeld übernehmen kann.

**Comment by thorol** [comment]
Bei mir auch, folgender Code wird bei mir für das Öffnen des Medienpools erzeugt: 

$mform->addMediaField(3,array('types'=>'gif,jpg,png','preview'=>1,'label'=>'Bild'));

![image](https://user-images.githubusercontent.com/25980352/87848556-bfd7a900-c8e1-11ea-983d-7086333a072a.png)
![image](https://user-images.githubusercontent.com/25980352/87848565-d0881f00-c8e1-11ea-85a0-ea87b26bcb91.png)

**Comment by thorol** [comment]
Habe jetzt in redaxo\src\addons\mform\lib\MForm\Parser\MFormParser.php Zeile 711 auskommentiert und funktioniert soweit alles. Wieso wird diese Zeile gebraucht?

**Comment by joachimdoerr** [comment]
27d9b249a255f320ac9397cadb92b4e3297d99e4
