### ISSUE TITLE
Testfälle

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mform#197]
Modul Tests aus den "Basis Beispielen": 

- [x] Text-Input- und Hidden-Elemente
- [x] Select- und Multiselect-Elemente
- [x] Checkbox und Radio-Elmente
- [x] Strukturelle Inline-Elemente
- [x] System-Button-Elemente
- [x] MForm-Widget-Elemente
 
Bitte beim Custom-Link Widgets alle Optionen Testen siehe: https://github.com/FriendsOfREDAXO/mform/blob/master/lib/MForm/MFormElements.php#L600

Modul Tests aus den "Erweiterte Beispiele": 

- [x] Attributes Method
- [x] Options Method
- [x] Parameter Method
- [x] Full JSON-Value-Support
- [ ] Wrapper-Elemente

Moul Tests aus den "Experten Beispiele":

- [x] Neue HTML5 Formular-Elemente
- [x] Datalists für Input-Elemente
- [x] Placeholder
- [ ] Parsley Validation

Wie vorgehen? 
1. MForm Master von GitHub downloaden
2. Installieren und die Beispiele Module nutzen zum testen
3. Testen und ggf. vorhandene Fehler hier Reporten
4. Wenn der Test für ein Beispiel Modul gut gelaufen ist in der Checkliste oben abhacken.

**Comment by crydotsnake** [comment]
Ich fange Jetzt mit dem Testen der Module an ! :).

**Comment by crydotsnake** [comment]
Fehlt bei dem Modul Strukturelle Inline-Elemente Vielleicht ein Ausgabe Code, oder verstehe ich das Modul Falsch?.

**Comment by joachimdoerr** [comment]
@crydotsnake ja es fehlen bei diversen Module die Outputs, die müsste man sich jeweils selbst zusammenbauen. Wenn du willst kannst du die Outputs als PR zurück liefern.

**Comment by crydotsnake** [comment]
Hm.. wie müssen die Outputs aussehen....

**Comment by crydotsnake** [comment]
Und welchen branch müsste ich mir klonen?. Denn Master, richtig?.

**Comment by skerbis** [comment]
Modul Tests aus den "Basis Beispielen": 

- [x] Text-Input- und Hidden-Elemente
- [x] Select- und Multiselect-Elemente
- [x] Checkbox und Radio-Elmente
- [ ] Strukturelle Inline-Elemente
- [ ] System-Button-Elemente
- [ ] MForm-Widget-Elemente
 
Bitte beim Custom-Link Widgets alle Optionen Testen siehe: https://github.com/FriendsOfREDAXO/mform/blob/master/lib/MForm/MFormElements.php#L600

Modul Tests aus den "Erweiterte Beispiele": 

- [ ] Attributes Method
- [ ] Options Method
- [ ] Parameter Method
- [ ] Full JSON-Value-Support
- [ ] Wrapper-Elemente
@skerbis testing

Moul Tests aus den "Experten Beispiele":

- [ ] Neue HTML5 Formular-Elemente
- [ ] Datalists für Input-Elemente
- [ ] Placeholder
- [ ] Parsley Validation

Wie vorgehen? 
1. MForm Master von GitHub downloaden
2. Installieren und die Beispiele Module nutzen zum testen
3. Testen und ggf. vorhandene Fehler hier Reporten
4. Wenn der Test für ein Beispiel Modul gut gelaufen ist in der Checkliste oben abhacken.

**Comment by skerbis** [comment]
Mform 6 ist released. Lasset die Issues kommen (oder auch nicht)
