### ISSUE TITLE
CUSTOM_LINK yform link wie bei cke5

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mform#200]

**Comment by joachimdoerr** [comment]
579d2f778fdf776b4fd7d3eceeab687bfd7ac9bb
ba4eefb36252a2fa45d48c7b870e728b96d39005
82b707d46662cff88d4b737040b34fd479e05175
49c03fd9ae36270045909d41941f554e04898575
dc8ed9e12747e9be5e5c34f8fb9438480d9d9ef2
e363a62f4fd8aa20818ac3ef8bcf57c6f6f65698

**Comment by joachimdoerr** [comment]
579d2f778fdf776b4fd7d3eceeab687bfd7ac9bb
ba4eefb36252a2fa45d48c7b870e728b96d39005
