### ISSUE TITLE
mform accordion font-awesome Problem

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/mform#202]
Scheinbar gibt es ein Problem mit:
font: normal normal normal 14px/1 FontAwesome;
Das Icon wird nicht angezeigt. Ich weiß aber nicht was es damit auf sich hat.
Wenn ich font-family einzeln deklariere funktioniert es.

**Comment by joachimdoerr** [comment]
@marcohanke kannst du mir dazu 1) ein Modul Input mit dem Problem liefern und 2) ein Modul Input mit deiner Lösung bereitstellen.

**Comment by skerbis** [comment]
Wegen Inaktivität geschlossen. Gerne wieder aufmachen, wenn wieder Infos vorliegen
