### ISSUE TITLE
Accordion Collapse Style

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/mform#203]
Beim Accordion hängen die Felder recht dicht am BTN. Außerdem fehlt optisch die Zugehörigkeit.
Hiermit sieht es besser aus: 

.mform .collapse {
    background: #fafafa;
    padding: 15px;
}
Willst du ein PR? Ich weiß nicht ob du collapse wonders auch noch verwendets und es dort stört?

**Comment by joachimdoerr** [comment]
Die Styles in der Beta sind noch nicht definiert.

**Comment by skerbis** [comment]
Danke ist angepasst.
