### ISSUE TITLE
CustomField vs. mblock zeigt falschen Eintrag

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/mform#204]
Gerade mit @skerbis getestet:
Ich habe ein Modul mit MForm/Mblock

```$mform = new MForm();
$id = '1';
$mform->addSelectField("$id.owlLoop",array('true' => 'Endlosschleife','false' => 'Nur einmal durchlaufen'),array('label'=>'Ablauf'));

$mblock = new MForm();
$id = '2';
$mblock->addCustomLinkField("$id.0.1",array('label'=>'Customlink', 'data-intern' => 'enable', 'data-media' => 'enable', 'data-mailto' => 'enable', 'data-phone' => 'enable'));
```

Ich füge das Modul hinzu und wähle ein Custom Link.
Ich speichere
Ich bearbeite das Modul erneut und füge einen weiteren MBlock hinzu.
Hier sehe ich den Link aus dem ersten Mblock obwohl das Feld leer sein sollte.
Ich klicke auf übernehmen und das Feld ist leer.
Das ganze kann ich beliebig wiederholen, es wird immer der Wert aus dem ersten Block angezeigt.

Technisch läuft also alles es landet auch nichts in der Ausgabe. Trotzdem verwirrt es

**Comment by skerbis** [comment]
In mform 6 bereits gefixt, zumindest tritt der Effekt nicht auf.
