### ISSUE TITLE
Version 6.x.x ::  mit mblock: Bildauswahl wirft js-Fehler

### ISSUE THREAD

**Issue by 191977** [FriendsOfREDAXO/mform#205]
Hi,
eben entdeckt:
wenn mform mit mblock und $mform->addMediaField(1, array('label'=>'Bild')); verwendet wird, geschieht beim Aufruf des Medienpools und dem klick auf "Übernehmen" nichts. 

Die Console wirft:
`
Uncaught TypeError: opener.document.getElementById(...) is null
    selectMedia https://www.domain.de/assets/addons/mediapool/mediapool.js?buster=1589319908:232
    onclick https://www.domain.de/redaxo/index.php?page=mediapool/media&opener_input_field=REX_MEDIA_1:1
mediapool.js:232:29
    selectMedia https://www.domain.de/assets/addons/mediapool/mediapool.js?buster=1589319908:232
    onclick https://www.domain.de/redaxo/index.php?page=mediapool/media&opener_input_field=REX_MEDIA_1:1
`

Tritt nur zusammen mit mblock auf. Zurück auf mform 5.3.1 läuft es wieder. Reproduziert auf ner frischen radaxo-Installation.

**Comment by joachimdoerr** [comment]
Hi @191977, welche MBlock Version verwendest du?

**Comment by 191977** [comment]
Hi @joachimdoerr,

habe es eben nochmal schnell nachvollzogen. Mit mblock 2.2.3 kommt der Fehler, mit 3.1.0 ebenso.
Ich habe eben auch noch gesehen, dass wenn im Modul direkt ein hinterlegtes Bild gelöscht werden soll, dass dann der Fehler kommt:
`Uncaught TypeError: a.obj is null
    deleteREXMedia https://www.domain.de/assets/addons/mediapool/mediapool.js?buster=1589319908:87
    onclick https://www.domain.de/redaxo/index.php?page=content/edit&article_id=1&slice_id=1&clang=1&ctype=1&function=edit#slice1:1
mediapool.js:87:5
    deleteREXMedia https://www.domain.de/assets/addons/mediapool/mediapool.js?buster=1589319908:87
    onclick https://www.domain.de/redaxo/index.php?page=content/edit&article_id=1&slice_id=1&clang=1&ctype=1&function=edit#slice1:1`

Außerdem ist mir noch aufgefallen, dass wenn außerhalb des blocks eine Media-Field vorhanden ist, die js-Fehler im block dann nicht mehr auftauchen. Gespeichert wird das ausgewählte Bild aber trotzdem nicht.

Hier noch mein Testmodul, vielleicht habe ich da auch einfach was falsches drin...
`<?php
$mform = new MForm();
$mform->addTextAreaField(1, 
        array(
        'label'=>'Text',
        'class'=>'cke5-editor', 
        'data-lang'=>\Cke5\Utils\Cke5Lang::getUserLang(), 
        'data-profile'=>'default')
        );
$mform->addMediaField(1, array('label'=>'Bild ohne mblock'));
echo $mform->show();

$id = 3;
$mform = new MForm();
$mform->addFieldset('Anker');
$mform->addTextField("$id.0.anchor", array('label'=>'Anker (opt.)'));
$mform->addFieldset('Text');
$mform->addTextField("$id.0.headline", array('label'=>'Headline'));
$mform->addTextField("$id.0.subheadline", array('label'=>'Sub-Headline'));
$mform->addTextAreaField("$id.0.text", 
        array(
        'label'=>'Text',
        'class'=>'cke5-editor', 
        'data-lang'=>\Cke5\Utils\Cke5Lang::getUserLang(), 
        'data-profile'=>'default')
        );
$mform->addFieldset('Bild');
$mform->addMediaField(1, array('label'=>'Bild'));
$mform->addMediaField(2, array('label'=>'Avatar'));
$mform->addLinkField(1,array('label'=>'Link'));

echo MBlock::show($id, $mform->show(), array('min'=>1,'max'=>30));
?>`

**Comment by skerbis** [comment]
Lässt sich bei mir mit diesem Code nicht reproduzieren.

**Comment by danspringer** [comment]
Kann ich so mit Rex 5.12 bestätigen.

Beim Medienpool kommt bei "Datei übernehmen" das folgende in der Browser-Konsole:

```
mediapool.js?buster=1616148315:232 Uncaught TypeError: Cannot set property 'value' of null
    at selectMedia (mediapool.js?buster=1616148315:232)
    at HTMLAnchorElement.onclick (index.php?page=mediapool/media&opener_input_field=REX_MEDIA_103330279651:286)
```

**Comment by danspringer** [comment]
```
<fieldset class="form-horizontal">

    <div class="form-group">
        <label class="col-sm-2 control-label">Überschrift</label>
        <div class="col-sm-10">
            <input class="form-control" name="REX_INPUT_VALUE[2]" value="REX_VALUE[2]" />
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Text</label>
        <div class="col-sm-10">
            <textarea class="form-control ckeditor" data-ckeditor-profile="standard" name="REX_INPUT_VALUE[3]">REX_VALUE[3]</textarea>
        </div>
    </div>

    <div class="form-group">

        <label class="col-sm-2 control-label">Button-Text</label>
        <div class="col-sm-10">
            <input class="form-control" name="REX_INPUT_VALUE[4]" value="REX_VALUE[4]" />
        </div>

        <label class="col-sm-2 control-label">Button-Link</label>
        <div class="col-sm-10">
            REX_LINK[id="2" widget="1"]
        </div>

    </div>

</fieldset>

<?php
$id = 1;

$mform = new MForm();

$mform->addFieldset('Feature');
$mform->addTab(Details);
$mform->addTextField("$id.0.title",array('label'=>'Titel'));
$mform->addMediaField("$id.0.img",array('label'=>'Bild'));
$mform->addLinkField("$id.0.link",array('label'=>'Link'));
$mform->addTab(Tags);
$mform->addTextField("$id.0.price",array('label'=>'Wert'));
$mform->addTextField("$id.0.button",array('label'=>'Button'));
$mform->addLinkField("$id.0.blink",array('label'=>'bLink'));

echo MBlock::show($id, $mform->show());

?>
```

**Comment by danspringer** [comment]
Es geht nur um den PHP-Teil von MForm/MBlock. Der Vollständigkeit halber, aber im Gesamtkontext.
Downgrade auf MForm 5.X hat geholfen.

**Comment by skerbis** [comment]
$mform->addMediaField("$id.0.img",array('label'=>'Bild'));
Mach mal 
$mform->addMediaField('1', array('label'=>'Bild'));

**Comment by danspringer** [comment]
Ja, das hilft :-)

**Comment by skerbis** [comment]
👍🏻

**Comment by skerbis** [comment]
@191977 Dein Code ist bei mir korrekt. Die Fehlermeldung taucht bei mir nicht auf. 
@danspringer  Hat hier das mediafeld falsch eingestellt.

**Comment by 191977** [comment]
Hi @skerbis,

tut mir leid, aber ich habe auf das betreffende System aufgrund persönlicher Veränderungen keinen Zugriff mehr. Insofern kannst du von meiner Seite aus zumachen. Aber vielen Dank fürs draufschauen.
