### ISSUE TITLE
Backend: Theme updaten / eigenes CSS verwenden

### ISSUE THREAD

**Issue by despecial** [FriendsOfREDAXO/mform#206]
Aktuell nicht gefunden wie man in MForm eigene Themes bzw CSS Styles einbinden kann.
So dass sie auch update-fähig sind. Gibt es die Möglichkeit und wenn ja, wie?

**Comment by skerbis** [comment]
Eigenes Theme anlegen im Data-Ordner. 
und im Projekt-AddOn 

$package = rex_addon::get('mform');
$package->setConfig('mform_theme', 'dein_theme');

eingeben. dein_theme durch deine Bezeichnung ersetzen
