### ISSUE TITLE
3.1.0 / Validation von Medialist hakt, wenn Textarea mit Validation folgt

### ISSUE THREAD

**Issue by rlfschmd** [FriendsOfREDAXO/mform#212]
Wen einem der Medialist folgenden Feld – z. B. einer Textarea – eine empty- oder minwords-Validation zugewiesen ist und das Feld nichts oder weniger als zwei Wörter enthält, wird nicht nur die Textarea zurecht als fehlerhaft markiert, sondern auch die davor stehende Medialist, obwohl Files eingetragen sind. Erst wenn man nochmal auf einen der Filenamen klickt, wird die Medialist wieder grün und das Modul lässt sich speichern. Für coole Checker nicht schlimm, aber vezagte Kunden weinen an der Stelle meistens. Hier der Code, bei dem es passiert:

```
$mform->addMedialistField(1)
->setParameters(array('types'=>'jpg, jpeg, png, gif', 'preview'=>1))
->setLabel('Bild/er*')
->addValidation('empty');

$mform->addTextAreaField(1)
->setLabel('Text*')
->addAttribute('class', 'markitupEditor-textile_custom')
->addValidation('empty')
->addValidation('minwords', 2);
```

**Comment by skerbis** [comment]
Parsley wird es in 6.0.0 nicht mehr geben
