### ISSUE TITLE
imagelist: es lassen sich nicht alle bilder löschen

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/mform#218]
in mform und yform lässt sich das letzte bild einer imagelist nicht löschen

REDAXO 5.12.0
MFORM 6.0.5

**Comment by skerbis** [comment]
Welcher Browser? Bei mir geht's in Safari, Chrome und FF

**Comment by isospin** [comment]
es scheint so als wenn sich das bild entfernen lässt - es wird via js aus dem widgezt entfernt. nach dem speichern/übernehmen ist es aber wieder da.
im ff, chrome und edge...

**Comment by skerbis** [comment]
stimmt.

**Comment by ynamite** [comment]
Fix:
in imglist.js auf Zeile 218 ergänzen:
```
 else {
	    element.find('input').val('');
}
```
