### ISSUE TITLE
type conversion verhindern die 2.

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/mform#226]
@skerbis 
Ich wollte eigentlich einen PR machen, habe mich aber verklickt und direkt nach master geschrieben:
in https://github.com/FriendsOfREDAXO/mform/blob/master/lib/MForm/Parser/MFormParser.php#L542 habe ich bei der `in_array` Abfrage das `(string)` reingesetzt. War das gleiche Problem wie #224.

**Comment by skerbis** [comment]
Danke 🙏 Ingo.
