### ISSUE TITLE
Linklist: fehlerhafte Darstellung von arabischen Schriftzeichen

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/mform#236]
`$mform->addLinklistField(1,array('label'=>'Links'));`
ein arabischer Artikelnane wird im Linklist Widget nur mit Fragezeichen dargestellt

`REX_LINKLIST[id="1" widget="1"]`
stellt den arabischen Artikelnamen korrekt dar

![mform_linklist 2021-11-10 110640](https://user-images.githubusercontent.com/1148347/141094459-68b2b2b3-2c6c-4823-ad95-ff68c0f6e43f.jpg)

**Comment by joachimdoerr** [comment]
a057c9ce8b1e74e992117350b45cfa445c563492
