### ISSUE TITLE
Validations funktionieren nicht mehr

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/mform#237]
Moin,
bisher konnte ich validations einfach an Textfelder oder ähnliches anhängen

```
$mform->addTextField("$id$sub.recipient",['label'=>'Emfpänger','style'=>'','class'=>'']);
$mform->addValidation('empty');
$mform->addValidation('email');
```

Das funktioniert so nicht mehr. Alle Validations werden ignoriert.

**Comment by skerbis** [comment]
jupp die gibts auch nicht mehr 
https://github.com/FriendsOfREDAXO/mform/releases/tag/6.0.0
