### ISSUE TITLE
Layout, Style und generell Optik verbessern

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mform#243]
- [x] Accordeons
- [x] Collapse
- [x] Inline Elemente

Es gibt sicher noch weitere Elemente die optisch überarbeitet werden sollten. Speziell im Kontext "Dark Theme" müsste hier sicher noch weiter Hand angelegt werden.

**Comment by skerbis** [comment]
noch was? :-)

**Comment by joachimdoerr** [comment]
- [ ] Tabs

**Comment by skerbis** [comment]
Sehen doch gut aus.

**Comment by joachimdoerr** [comment]
top dann close. und vielen Dank @skerbis
