### ISSUE TITLE
json wird nicht korrekt decodiert in MFormValueHandler

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/mform#246]
Ich hatte hier einen Fall, bei dem im Input Quotes in Quotes waren, ungefähr so: `title=\"&quot;Blabla&quot;\"`
Das führte zu Bruch, weil der MFormValueHandler `&quot;` zu echten Doublequotes umgewandelt hat und dann json_decode gestolpert ist und kein Array daraus gemacht hat.

Folgender Patch hat das Problem behoben:

Zeile 53:

```
                        $jsonResult = json_decode(htmlspecialchars_decode($result['value'][$i],ENT_NOQUOTES), true); // wb
//                       $jsonResult = json_decode(htmlspecialchars_decode($result['value'][$i]), true);

```

Ich kann natürlich nicht behaupten, ob diese Anpassung nachhaltig ist.

**Comment by dtpop** [comment]
Oooh git hat mein Beispiel geshreddert ...
Ich versuchs nochmal:
`title="&quot;Blabla&quot;"`

**Comment by joachimdoerr** [comment]
Das Problem tritt aber nur im Zusammenhang mit rex array_values auf oder?

**Comment by joachimdoerr** [comment]
8bbe02acd971996155ed3ca3b73bc8b606abebf0
