### ISSUE TITLE
multilanguage Formulare

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mform#248]
Support für mehrsprachige Formulare wären echt toll

**Comment by joachimdoerr** [comment]
Gibts schon: `$mform->addTextAreaField(1, ['label' => ['en'=>'Label EN', 'de' => 'Label DE']]);`

**Comment by joachimdoerr** [comment]
Wegen Inaktivität (fehlendes Mitwirken) der Community an der Stelle closed.

**Comment by skerbis** [comment]
Bitte offen lassen. Es muss noch in die Doku

**Comment by alxndr-w** [comment]
Wäre es nicht einfacher, hier als Entwickler `rex_i18n::msg("label")` zu verwenden und die Logik aus MForm zu streichen? Das wirkt auf mich redundant und komplex, auch in der Handhabung / Pflege, falls mal eine neue Sprache hinzukommt oder entfernt wird.

**Comment by alxndr-w** [comment]
Ich bin in der Doku auf Mehrsprachigkeit eingegangen.
