### ISSUE TITLE
Wrapper-Elemente in Wrapper-Elementen funktionieren nicht zuverlässig

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mform#251]
Wenn ein Collapse Element in einem Tab eingesetzt wird führt das zu Problemen. Nach dem Speichern ist der Collapse geschlossen statt offen. 

- [x] Checkbox-Collapse in Tab
- [x] Toggle-Checkbox-Collapse in Tab
- [x] Select-Collapse in Tab
- [x] Radio-Collapse in Tab
- [x] Checkbox-Collapse in Collapse
- [x] Toggle-Checkbox-Collapse in Collapse
- [x] Select-Collapse in Collapse
- [x] Radio-Collapse in Collapse
- [x] Checkbox-Collapse nested
- [x] Toggle-Checkbox-Collapse nested
- [x] Select-Collapse nested
- [x] Radio-Collapse nested
- [x] Tab in Collapse
- [x] Tab in Tab

**Comment by joachimdoerr** [comment]
Demo Modul für alle die gerne testen wollen: 
`if (!function_exists("getTxtInput")) {
    function getTxtInput($id, $full = false): \MForm\MFormElements
    {
        return MForm::factory()->addTextAreaField("4.0.$id", ['label' => 'Text-Area ' . $id, 'full' => $full]);
    }
}
if (!function_exists("getCheckboxToggleDemo")) {
    function getCheckboxToggleDemo($id, $toggle = false, $form = null): \MForm\MFormElements
    {
        $method = (!$toggle) ? 'addCheckboxField' : 'addToggleCheckboxField';
        $uniq = uniqid('collapse');
        return MForm::factory()->addFieldsetArea('Toggle checkbox collapse element',
            MForm::factory()
                ->$method("4.0.$id", [1 => 'Open Collapse-area'], ['label' => 'Collapse checkbox', 'data-toggle-item' => $uniq])
                ->addForm(
                    MForm::factory()->addCollapseElement('', ((is_null($form)) ? getTxtInput("$id" . "2") : $form), false, true, ['data-group-collapse-id' => $uniq])
                )
        );
    }
}
if (!function_exists("getSelectToggleDemo")) {
    function getSelectToggleDemo($id, $count = 3, $radio = false)
    {
        $options = (!$radio) ? [0 => "Bitte wählen"] : [];
        $toggleOptions = [];
        $mform = MForm::factory();
        if (is_array($count)) {
            foreach ($count as $key => $element) {
                $i = $key+1;
                $options[$key] = 'collapse ' . $i;
                $toggleOptions[$key] = 'collapsee' . $i;
                $mform->addCollapseElement('', $element, false, true, ['data-group-collapse-id' => 'collapsee' . $i]);
            }
        } else {
            for ($i = 1; $i <= $count; $i++) {
                $options[$i] = 'collapse ' . $i;
                $toggleOptions[$i] = 'collapse' . $i;
                $mform->addCollapseElement('', getTxtInput("$id" . $i), false, true, ['data-group-collapse-id' => 'collapse' . $i]);
            }
        }
        if ($radio) $options[] = 'Something...';
        $method = (!$radio) ? 'addSelectField' : 'addRadioField';
        return MForm::factory()
            ->addFieldsetArea(((!$radio) ? 'Select' : 'Radio') . ' collapse element',
                MForm::factory()
                    ->$method("4.0.$id", $options, ['label' => ((!$radio) ? 'Select' : 'Radio') . ' collapse'])
                    ->setToggleOptions($toggleOptions)
                    ->addForm($mform)
            );
    }
}

echo getSelectToggleDemo(0, [getCheckboxToggleDemo(311), getCheckboxToggleDemo(322, true), getSelectToggleDemo(333), getSelectToggleDemo(344, 3, true)])->show();
echo getSelectToggleDemo(0, [getCheckboxToggleDemo(511), getCheckboxToggleDemo(522, true), getSelectToggleDemo(533), getSelectToggleDemo(544, 3, true)], true)->show();
echo getCheckboxToggleDemo(6780, false, getCheckboxToggleDemo(670))->show();
echo getCheckboxToggleDemo(6781, true, getCheckboxToggleDemo(671))->show();

$mform = MForm::factory();
foreach ([getCheckboxToggleDemo(411), getCheckboxToggleDemo(422, true), getSelectToggleDemo(433), getSelectToggleDemo(444, 3, true)] as $key => $element) {
    $mform->addCollapseElement('Collapse ' . $key, $element);
}

$mform = MForm::factory()
    ->addForm($mform)
    ->addTabElement('Checkbox', getCheckboxToggleDemo(111), true)
    ->addTabElement('Checkbox2', getCheckboxToggleDemo(122))
    ->addTabElement('Toggle', getCheckboxToggleDemo(133, true))
    ->addTabElement('Toggle2', getCheckboxToggleDemo(144, true))
    ->addTabElement('Select', getSelectToggleDemo(155, 4))
    ->addTabElement('Select2', getSelectToggleDemo(166, 2))
    ->addTabElement('Radio', getSelectToggleDemo(177, 3, true))
    ->addTabElement('Radio2', getSelectToggleDemo(188, 2, true))
    ->addTabElement('Tab', MForm::factory()
        ->addTabElement('Tab', getTxtInput(222, true), true)
        ->addTabElement('Tab2', getTxtInput(233, true))
    );

echo MBlock::show(4, $mform);
`

**Comment by joachimdoerr** [comment]
73d213edc824dbab8e541e20045e5fc123886b01
840ec99bd3f1f11d6a43f967082a6cdfc04ba45f

**Comment by skerbis** [comment]
Danke. Getestet. Funzt super. 👍🏻
