### ISSUE TITLE
PHP Version in der package.yml anheben? -  Exception: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/mform#256]
https://github.com/redaxo/redaxo/issues/5090

> Hallo, beim Update auf mForm 7.0.0 kommt dieser Fehler unter PHP 7.3.33. Unter PHP 7.4.28 geht es tadellos.
> 
> Anbei der Report:
> 
> **Request-Uri:** /redaxo/index.php?page=content/edit&article_id=65&mode=edit&slice_id=175&clang=1&ctype=1&function=edit **Request-Method:** GET
> 
> **ParseError:** syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) **File:** redaxo/src/addons/mform/lib/MForm/MForm.php **Line:** 19

**Comment by gharlan** [comment]
Das Addon gibt an, PHP 7.3 zu unterstützen, verwendet aber schon Typed Properties (PHP >= 7.4).
