### ISSUE TITLE
MForm 7: setHiddenField erzeugt eine komplette form-group

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/mform#257]
Mit setHiddenField erzeugte Input-Felder werden mit dem kompletten HTML der form-group und leerem Label ausgegeben. Dadurch erzeugen die Felder sichtbare Leerzeilen im Formular. 
Es wirkt auf mich, als würde diese Variable nie ausgewertet: https://github.com/FriendsOfREDAXO/mform/blob/e75a311bcf5eddd91a0abcb29735104359b1cd53/lib/MForm/Parser/MFormParser.php#L180

**Comment by joachimdoerr** [comment]
d10daa4f12ee56548b2d601a27f6edd708356589
