### ISSUE TITLE
Doku an allg. Doku-Schema für REDAXO angleichen 

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/mform#258]
Was mich an der sonst sehr gelungenen Doku mit Code-Beispielen stört ist dieses stetige Suchen und Auf-/Zuklappen von Elementen, während ich gerne die browsereigene Suchfunktion benutzen möchte, um schnell an meinen Baustein zu kommen.

Wäre es gewünscht, die Doku an das anzugleichen, was ich sonst bei YForm/YCom/YRewrite/YForm Spam Protection/Eigenen Addons gemacht habe? Alles als passende Markdown-Dateien rendern lassen?

**Comment by joachimdoerr** [comment]
@alxndr-w die Beispiele werden automatisch anhand von hinterlegten ini Files generiert, ich denke das ist nicht so easy umzubauen.
