### ISSUE TITLE
MForm 7.1.1: Selects erhalten falsches Attribut

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/mform#263]
Diese Zeile https://github.com/FriendsOfREDAXO/mform/blob/40ef8f4d5554ae54ee80235408d47fcbea173ce6/lib/MForm/Parser/MFormParser.php#L295 sorgt dafür, dass `data-toggle="collapse"` an jedes Select-Element gehängt wird, unabhängig davon, ob es benötigt wird, oder nicht. Das hat zur Folge, dass hier https://github.com/FriendsOfREDAXO/mform/blob/40ef8f4d5554ae54ee80235408d47fcbea173ce6/assets/mform.js#L48-L53 alle Event-Listener, die evtl. zusätzlich zu denen von MForm verwendet werden, auch vom Select entfernt werden. 
 
Aus meiner Sicht sollte das `data-toggle`-Attribut nur vergeben werden, wenn tatsächlich Toggle-Optionen existieren.

Evtl. ist es auch nicht verkehrt, für MForm-Event-Listener generell einen eigenen Namespace zu verwenden und nur den zu löschen, und nicht pauschal alle Event-Listener zu entfernen.

**Comment by joachimdoerr** [comment]
@DanielWeitenauer das Attribute wird doch nur geschrieben wenn `getToggleOptions >= 0` ist.

**Comment by DanielWeitenauer** [comment]
@joachimdoerr das ist nicht ganz richtig. Die Zeile wird ausgeführt, wenn die Größe (`sizeof`) von getToggleOptions >= 0 ist, also immer.

**Comment by joachimdoerr** [comment]
@DanielWeitenauer kannst du mir bitte ein Modul Beispiel geben oder nochmal nach prüfen. Ich kann keine ungewünschten `data-toggle="collapse"` ausmachen.
<img width="1110" alt="Bildschirmfoto 2024-05-13 um 22 40 57" src="https://github.com/FriendsOfREDAXO/mform/assets/1191549/dfc2aa09-3368-4aaa-9c04-4a3cc2ce2fa9">

**Comment by DanielWeitenauer** [comment]
@joachimdoerr Die fehlerhafte Zeile wurde in diesem Commit angepasst: 90d62d943099ae8a1c07add6c4f7f1e0c38e30bf. Das Attribut wird nun nur noch gesetzt, wenn es tatsächlich vorhanden ist. Das Problem sollte also erledigt sein.
