### ISSUE TITLE
Doku ohne Verkettung

### ISSUE THREAD

**Issue by akuehnis** [FriendsOfREDAXO/mform#264]
Hallo Leute

Mit der Version 7 des (absolut genialen) Addons ist man in der Dokumentation zur Code-Darstellung als Verkettung übergegangen. Ich finde dies ist schlechter lesbar, komplizierter aufzubauen und macht die Wiederverwendung von Elementen schwieriger.

Daher rege ich an, in der Dokumentation wieder eine traditionellere Form zu wählen.

Zum Beispiel für Tabs:

```
// initiere MForm
$mform = MForm::factory();

// erster Tab
$tab = MForm::factory();
$tab->addTextField('2.0.1',['label' => 'Text1']);
$tab->addTextField('2.0.2',['label' => 'Text2']);
$mform->addTabElement('Tab1', $tab, /*active*/ false, /*align right*/ false);
            
// zweiter Tab, aktiv und nach rechts verschoben 
$tab = MForm::factory();
$tab->addTextField('2.0.3',['label' => 'Text3']);
$mform->addTabElement('Tab2', $tab, /*active*/ true, /*align right*/ true);

// dritter Tab
$tab = MForm::factory();
$tab->addTextField('2.0.4',['label' => 'Text4']);
$mform->addTabElement('Tab2', $tab, /*active*/ false, /*align right*/ false);

// parse mform
echo $mform->show();
```

**Comment by joachimdoerr** [comment]
@akuehnis gerne via PR

**Comment by joachimdoerr** [comment]
Die Doku wurde für MForm 8 von @alexwenz überarbeitet. Sofern kein anderer PR mehr kommt schließe ich hier mal.
