### ISSUE TITLE
addDescription berücktsichtigt nicht setFull

### ISSUE THREAD

**Issue by Sysix** [FriendsOfREDAXO/mform#265]
Wenn das Input volle Breite hat, sieht die Beschreibung komisch aus, da ein Offset definiert wird:

![grafik](https://user-images.githubusercontent.com/3897725/181550224-65f08e20-e837-4a68-96ca-95d279864202.png)

        $buttonForm->addInputField('url', "xxxxx");
        $buttonForm->setLabel('Externer Link');
        $buttonForm->setFull();
        $buttonForm->addDescription("URL bitte mit https:// angeben");

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/d80a76618d70ba0ad4524fc45ac73c11c0a28399
