### ISSUE TITLE
PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mform#268]
17.08.2022, 16:27:34 | Deprecated | htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated | redaxo/src/addons/mform/lib/MForm/Utils/MFormItemManipulator.php | 26
-- | -- | -- | -- | --
17.08.2022, 16:27:34 | Deprecated | str_replace(): Passing null to parameter #3 ($subject) of type array\|string is deprecated | redaxo/src/addons/mform/lib/MForm/MFormElements.php | 96

**Comment by joachimdoerr** [comment]
3b1c6c62997c3beb78e884f3f175015ce7e5fafa
