### ISSUE TITLE
Argument 1 must be type of string, null given

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/mform#269]
https://github.com/FriendsOfREDAXO/mform/blob/8e9ed2cddfa512d1f0184912f254e5034768ef55/lib/MForm/MFormElements.php#L232-L237

wenn addFieldsetArea() ohne Value aufgerufen wird.

**Comment by skerbis** [comment]
danke, welchen Sinn macht ein Fieldset ohne Value?

**Comment by alxndr-w** [comment]
Soweit ich mich erinnere in der Optik eine Trennlinie oder einen Rahmen, manchmal immerhin eine logische Gruppierung im HTML. Für mich gäbe es keinen Grund, dass es das nicht darf.

**Comment by alxndr-w** [comment]
Hoppla. 

Wollte es gerade fixen, habe aus Versehen direkt committet (Sorry!) und lasse jetzt die Finger davon, da ihr sowie an einer neuen Version arbeitet.

Wäre super, wenn Legends jetzt auch leer bleiben dürfen.
