### ISSUE TITLE
Tests hinzufügen

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/mform#273]
**Feature description / Feature Beschreibung**
Bei so einem weit verbreitetem Addon wäre es sicher gut wenn man die Funktionalitäten über Unit/E2E-Tests prüft. 
Oder auch prüfen ob der Code korrekt formatiert ist. Siehe z.B.:
https://github.com/eaCe/yform_seeder/blob/master/.github/workflows/phpchecks.yml#L70

**Comment by skerbis** [comment]
@eaCe leg los

**Comment by eaCe** [comment]
Warum schlage ich denn sowas vor... ;) Ich kann anfangen, kenne MForm aber nicht sehr gut.

**Comment by skerbis** [comment]
Ich auch nicht 😂
