### ISSUE TITLE
Update 7.2.3 Values vom nachfolgenden Modul werden übernommen

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/mform#275]
**Description / Beschreibung**
Die Multiselect-Sache funktioniert jetzt super, aber beim Hinzufügen von Modulen werden die jeweils aus einem eventuell nachfolgenden Modul in das neue übernommen.

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.1
PHP: 8.1.1
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**Comment by skerbis** [comment]
in mblock oder mform?

**Comment by skerbis** [comment]
@fietstouring wie kann ich das reproduzieren? Hast du ein Beispiel?

**Comment by fietstouring** [comment]
also bei mir übernehmen mform Formulare mit dem Update 7.3.2 die Values aus einem nachfolgenden Modul. Bei dem Editor steht der Text in VALUE[1].
```
$mform = MForm::factory();
$mform->addTextField(1);
```

![Bildschirmfoto 2022-11-22 um 08 42 41](https://user-images.githubusercontent.com/1846849/203254851-22f2502a-8a74-4e3b-8349-7ce87677a8d7.png)

**Comment by alxndr-w** [comment]
Kann ich bestätigen, bzw. eine Kundin von mir.

**Comment by ischfr** [comment]
Ist bei mir auch so. 

Wenn ich mit 7.2.3 in einem Artikel einen neuen Block **zwischen** bestehenden Blöcken anlege, dann werden anscheinend die Felder dieses neuen Blocks mit den Werten des nachfolgenden Blocks vorbelegt, sofern der Folgeblock dieselben Rex-Values nutzt.

Habe nun wieder MForm 7.2.2 installiert, und dort existiert das Problem bei mir nicht.

**Comment by skerbis** [comment]
@fietstouring 

Kannst du bitte testen?

Ersetze 
https://github.com/FriendsOfREDAXO/mform/blob/944e8aba721e8ed672db01660762014b81f8cd19/lib/MForm/MFormElements.php#L43

bitte durch: 

```php
        if ((rex_request('function', 'string') === 'edit' && rex_request('function', 'string') != 'add') || (\rex_be_controller::getCurrentPage() === 'content/edit' && rex_request('function', 'string') != 'add')) {
```

**Comment by fietstouring** [comment]
in meiner Testumgebung tritt der Fehler damit nicht mehr auf!

**Comment by alxndr-w** [comment]
@skerbis ist eingebaut, ich gebe Rückmeldung...

**Comment by ischfr** [comment]
bei mir sieht's so weit gut aus. 

Habe auf dem Testsystem eben erst mal 7.2.3. installiert, das ursprüngliche Problem noch mal bestätigt und dann den Fix eingesetzt. Danach an den gleichen Stellen wieder getestet und es scheint bei mir nun nicht mehr vorzukommen!

**Comment by skerbis** [comment]
ok ... 4 Augen reichen mir. Release kommt.
