### ISSUE TITLE
MultipleSelects mit per Default selektierten Optionen?

### ISSUE THREAD

**Issue by ischfr** [FriendsOfREDAXO/mform#278]
Es scheint in der aktuellen **MForm-Version 7.2.4** nicht möglich zu sein, bei einem MultipleSelect die **Options gleich als "selected" zu definieren**. 

Anscheinend ist zwar – wie beim einfachen Select – ein "defaultValue"-String vorgesehen, ich konnte damit aber keine Auswirkungen auf ein Multiselect feststellen. 

Ein einzelner Default-Wert würde hier auch nicht genügen, da ja potenziell mehrere Values ( bzw. deren Options) mit "selected" markiert werden sollen.

**Comment by alxndr-w** [comment]
Hast du's mal kommagetrennt versucht, also "1,4,5" bzw. "Option1,Option2,Option3"?

**Comment by ischfr** [comment]
Hab es gerade mal so versucht:

`->addMultiSelectField(7, ['autoplay'=>'Automatisch abspielen', 'loop'=>'Endlosschleife', 'controls'=>'Player Bedienelemente', 'muted'=>'Ohne Sound'], ['label' => 'Abspiel Optionen', 'default-value' => 'loop, muted'])`

Es ist die selbe Form, die ich auch bei einfachen Selects nutze. Habe mehrere Values wie vorgeschlagen kommagetrennt aufgeführt. Das hat aber leider keine Auswirkungen gehabt.

**Comment by ischfr** [comment]
Mein Test von letzter Woche war übrigens bereits mit der Version 8 beta. 

Ich bin halt immer noch nicht sicher, ob ich da grundsätzlich etwas falsch mache, oder ob default-value an dieser Stelle noch nie funktioniert hat. 

Ich habe dazu für Multiselect m.W. auch noch nie Code-Beispiele gesehen.

**Comment by joachimdoerr** [comment]
Default Value für Multiple Selects haben noch nie funktioniert. Ich hab das jetzt mal hinzugefügt, bitte Testen b8141ba02ac9538680492f873d7a3729dd9ea954

**Comment by ischfr** [comment]
Ich hab es gerade mal mit meinem o.g. Code-Beispiel ausprobiert. Der erste Wert wird gesetzt, alles danach wird ignoriert. Ich schaffe es also nach wie vor nicht, mehrere Werte zu setzen. Oder muss ich die anders notieren?

**Comment by alxndr-w** [comment]
Versuch es bitte ohne Leerzeichen nach dem Komma

**Comment by ischfr** [comment]
ah! Das hat funktioniert! Vielen Dank, dann funktioniert es doch!
Das wäre vielleicht eine Erwähnung oder ein Beispiel in der Doc wert, dass man hier auf zusätzliche Leerzeichen achten muss.

**Comment by alxndr-w** [comment]
Naja, eigentlich sind kommagetrennte Werte immer ohne Leerzeichen

**Comment by skerbis** [comment]
Es ist durchaus möglich dass Werte mit Leerzeichen beginnen. Daher macht es genau das was es soll

**Comment by alxndr-w** [comment]
So meinte ich das auch.
