### ISSUE TITLE
addImagelistField erfordet ID als String

### ISSUE THREAD

**Issue by akuehnis** [FriendsOfREDAXO/mform#280]
**Description / Beschreibung**

addImagelistField erfordert, dass die ID des Feldes als String übergeben wird. Wenn die ID des Feldes als Integer übergeben wird, dann werden die ausgewählten Bilder nicht gespeichert.

Die Anzeige des Bilder-Auswahl-Widgets funktioniert aber in beiden Fällen.

Mit der ID als Integer funktioniert es nicht:
```
$mform->addImagelistField(2, ['label' => 'Image List']);
```

Dies funktioniert:
```
$mform->addImagelistField("2", ['label' => 'Image List']);
```

**Affected versions / Verwendete Versionen**

MForm: 7.2.5
REDAXO 5.14.2
PHP 8.1.12
MariaDB 10.3.37

**Comment by eaCe** [comment]
@akuehnis das Problem kann ich mit der aktuellen Version nicht reproduzieren.

**Comment by skerbis** [comment]
Falls es hier weiterhin Probleme gibt, gerne wieder öffnen.
