### ISSUE TITLE
Inhalt wird nicht mehr angezeigt nach Update von 7.2.4 auf 7.2.5

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/mform#281]
Nach dem Update von 7.2.4 auf 7.2.5: Beim Editieren von Blöcken wird der vorhandene Inhalt nicht mehr geladen/gezeigt/gespeichert.

Verantwortlich dafür ist wsl. diese Stelle:

https://github.com/FriendsOfREDAXO/mform/commit/af092efaa9d7faaa414ae4cee62a2e160887d220

Wenn man den Commit rückgängig macht, klappt es wieder.

Ansonsten klappt es auch so:
```
if(!is_int($id)) {
    str_replace(',', '.', $id);
}
```

**Affected versions / Verwendete Versionen**
V 7.2.5

**Comment by skerbis** [comment]
Danke: https://github.com/FriendsOfREDAXO/mform/releases/tag/7.2.6
