### ISSUE TITLE
Multiselect speichert Werte nicht

### ISSUE THREAD

**Issue by MC-PMOE** [FriendsOfREDAXO/mform#283]
**Description / Beschreibung**

Verwendet man die nachfolgende Schreibweise für die ID:
`->addMultiSelectField("1.0.locations", $locations, ["label" => "Standorte"])`
Werden die Werte nicht richtig gespeichert. Wählt man keine Option aus setzt er alle Optionen sowohl beim speichern als auch beim Übernehmen.

Mit dieser Schreibweise funktioniert es:
`->addMultiSelectField("1.locations", $locations, ["label" => "Standorte"])`

Ich erinnere mich da dunkel an folgendes Issue #233 
Vielleicht ähnelt sich die Ursache.

**Affected versions / Verwendete Versionen**
7.2.7

REDAXO: 5.15.0-dev
PHP: 8.0.28
Database: MariaDB 10.5.18
Browser: Firefox 111.0b3

**Comment by alxndr-w** [comment]
Im Zusammenhang mit dem Feld #278 vielleicht was im Argen?

**Comment by joachimdoerr** [comment]
Ich kann den Fehler mit der aktuellen Beta nicht nachstellen.
