### ISSUE TITLE
`translate:` für Labels, Fieldset-Titel usw. ermöglichen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/mform#288]
**Feature description / Feature Beschreibung**
```
$mform->addTextField(1, ['label' => 'translate:headline']);
```

Parameter wie `label` sollten deren Werte (hier `translate: headline`) durch die passende rex_i18n-Methode schleusen.

**Comment by joachimdoerr** [comment]
Für Label sollte es da schon was geben: `$mform->addTextField(1, ['Label' => ['de' => 'Label de', 'en' => 'Label en']]);`

**Comment by alxndr-w** [comment]
Das ist ein guter Workaround. Mein Ziel wäre, dass sich mform im Verhalten da rex_form angleicht und es ist natürlich komfortabel, da nur `translate:` eintippen zu müssen.
