### ISSUE TITLE
item-col-class/label-col-class/setLabelColClass() und setFormItemColClass() werden nicht berücksichtigt

### ISSUE THREAD

**Issue by Neicul** [FriendsOfREDAXO/mform#289]
Will man ein Select-Feld mit item-col-class/label-col-class/setLabelColClass() oder setFormItemColClass() anpassen, wird dieser Wert mit Standard-Werten überschrieben.

Getestet hab ichs nur mit Select-Feldern aber gilt wahrscheinlich für mehr Input-Types

**Comment by joachimdoerr** [comment]
@Neicul hast Du da ein Beispiel Code?

**Comment by joachimdoerr** [comment]
@Neicul bitte ein Beispiel Code bereitstellen und dann nochmal öffnen.
