### ISSUE TITLE
Creation of dynamic property rex_fragment::$formItemColClass is deprecated

### ISSUE THREAD

**Issue by akrys** [FriendsOfREDAXO/mform#297]
Hab gerade wegen `usage_check` mit `mform` experimentiert. Dabei schaue ich auch, ob etwas in die Error-Logs geschrieben wird.

Dabei ist mir eine `mform` Deprecation aufgefallen:

>Creation of dynamic property rex_fragment::$formItemColClass is deprecated
Datei: redaxo/src/addons/mform/fragments/default_theme/mform_default.php:6
URL: http://localhost:30080/redaxo/index.php?page=content/edit&article_id=20&mode=edit&slice_id=149&clang=1&ctype=1&function=edit

Heißt: Lokale Variablen in Fragmenten sollten nicht nach `$this` geschrieben werden.

| Name | Version |
|--------|--------|
| REDAXO | 5.15.1 |
| PHP | 8.2.3 |

**Comment by joachimdoerr** [comment]
83762353c1bcb00abbf07146f92de73114c14584

wird im nächsten release gefixt sein.
