### ISSUE TITLE
uploader_options is not defined, wenn filetypes=*

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mform#301]
**Description / Beschreibung**
ich bin unsicher, ob das Problem bei yform, mform oder bei uploader liegt. Vermutlich bei mform und/oder yform.
Wenn der Medienpool über ein yform Table Manager imagelist-Feld öffnen, wird Uploader nicht angezeigt.
In der Konsole steht 
`Uncaught SyntaxError: Invalid regular expression: /(\.|\/)(*)$/i: Nothing to repeat`
`uploader_options is not defined`

Bei einem Media-Feld, in Modul-Eingaben (egal ob Media, Medialist oder Imagelist) oder direkt über den Medienpool funktioniert uploader normal.

https://github.com/FriendsOfREDAXO/uploader/issues/80

**Affected versions / Verwendete Versionen**
uploader 2.4.2
mform 7.3.0
yform 4.1.2-beta2

<details>
<summary>System report (REDAXO 5.15.1, PHP 8.3.0, MySQL 8.0.33)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.3.0                          |
|       OPcache | yes                            |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 8.0.33 |
| Character set | utf8mb4      |

| Server        |              |
| ------------: | :----------- |
|            OS | Darwin       |
|          SAPI | fpm-fcgi     |
|     Webserver | nginx/1.22.1 |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/121.0.0.0 |
|      Protocol | HTTP/1.1         |
|         HTTPS | no               |

| Packages                   |             |
| -------------------------: | :---------- |
|                    adminer | 1.9.3       |
|                     backup | 2.9.0       |
|                   be_style | 3.2.0       |
|            be_style/redaxo | 3.2.0       |
|                   be_tools | 1.8.0       |
|                    bloecks | 3.1.1       |
|           bloecks/cutncopy | 3.1.1       |
|          bloecks/dragndrop | 3.1.1       |
|             bloecks/status | 3.1.1       |
|                    cropper | 2.0.3       |
|                  developer | 3.9.2       |
|            emailobfuscator | 3.0.0       |
|                 focuspoint | 4.1.0       |
|                 hyphenator | 1.3.0       |
|                    install | 2.11.1      |
|                     massif | 1.0.0       |
|            massif_settings | 1.0.0       |
|                     mblock | 3.4.13      |
|              media_manager | 2.14.0      |
|   media_manager_responsive | 1.1.5       |
|           media_negotiator | 4.0.4       |
|                  mediapool | 2.13.0      |
|                   metainfo | 2.10.0      |
|                      mform | 7.3.0       |
|                       plyr | 3.23.4      |
|                    project | dev         |
|           quick_navigation | 6.1.0       |
|                      sprog | 1.5.1       |
|                 statistics | 3.1.0       |
|                  structure | 2.15.0      |
|          structure/content | 2.15.0      |
|           structure_tweaks | 1.4.1       |
|                   tinymce5 | 1.2.17      |
|                   ui_tools | 1.2.2       |
| ui_tools/jquery-minicolors | 2.4.0       |
|         ui_tools/selectize | 0.2.0       |
|                   uploader | 2.4.2       |
|                        url | 2.1.0       |
|                  useragent | 2.3.0       |
|                      users | 2.10.0      |
|                     watson | 2.3.0       |
|                    ydeploy | 2.0.0       |
|                      yform | 4.1.2-beta2 |
|                yform/email | 4.1.2-beta2 |
|              yform/manager | 4.1.2-beta2 |
|                yform/tools | 4.1.2-beta2 |
|              yform_adminer | 1.2.0       |
|           yform_quick_edit | 1.0.1       |
|      yform_spam_protection | 1.2.3       |
|            yform_usability | 2.1.4       |
|                   yrewrite | 2.10.0      |

</details>

**Did it whoops? / Whoops erhalten?**
Nope

**Comment by ynamite** [comment]
Fehler gefunden, liegt scheinbar an mform. Wenn mals `Erlaubte Dateien` einfach ein Asterisk `*` eingibt, hängt sich das imagelist-Feld auf. Ob das ein Bug ist, sei dahingestellt ;)

**Comment by skerbis** [comment]
@ynamite wusste garnicht dass * eine mögliche Eingabe ist. Wo ist das dokumentiert?

**Comment by joachimdoerr** [comment]
@ynamite magst Du dir das Problem näher anschauen ich wäre froh für jede Hilfe

**Comment by ynamite** [comment]
https://github.com/FriendsOfREDAXO/mform/pull/326
