### ISSUE TITLE
customLink `ylink` funktioniert nicht mehr mit yform 4.2.0

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mform#306]
**Description / Beschreibung**

Das Popup öffnet sich zwar, aber beim Versuch einen Datensatz auszuwählen, erscheint in der Konsole
```
Uncaught TypeError: Cannot set properties of null (setting 'value')
```

yform manager triggered den Event `rex:YForm_selectData` nicht mehr.

**Affected versions / Verwendete Versionen**
yform 4.2.0
mform 7.4.0

**Comment by skerbis** [comment]
bitte auch bei yForm posten

**Comment by ynamite** [comment]
Schon passiert ;)

**Comment by ynamite** [comment]
https://github.com/yakamara/yform/pull/1484
