### ISSUE TITLE
addImagelistField funktioniert nicht mit gridblock

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mform#312]
Medienpool lässt sich nicht öffnen

![image](https://github.com/FriendsOfREDAXO/mform/assets/330516/ed747a36-7842-445b-9ee8-61e7aea7b9bf)

als alleiniges Modul funktioniert es

**Comment by skerbis** [comment]
Hat es vorher funktioniert?

**Comment by olien** [comment]
Weiß nicht. Hans noch nie genutzt. Das custom link Feld funktioniert

**Comment by skerbis** [comment]
Das Widget wird wohl auch nie mit Gridblock funktionieren.

**Comment by olien** [comment]
😢
