### ISSUE TITLE
Reihenfolge customlink 

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mform#314]
![image](https://github.com/FriendsOfREDAXO/mform/assets/330516/81bc2afa-59de-4e06-a95f-16ae128a8b6b)

Wäre es nicht ggf so "schöner"

interner Link, externer link, Datei, yform, E-Mail, Tel

oder kann ich die Reihenfolge beeinflussen

**Comment by skerbis** [comment]
Die Reihenfolge ist fest.  Danke für die Anregung.
