### ISSUE TITLE
MForm 8 Beta - Repeater: Neu-Anlage mehrerer Leerblöcke auf einmal

### ISSUE THREAD

**Issue by ischfr** [FriendsOfREDAXO/mform#325]
Wie kann man erreichen, dass bei Neu-Anlage von Repeater-Blöcken mit gleichzeitig gesetztem Min-Wert die entsprechende Anzahl an Blöcken auf einmal angelegt wird?

Die Frage könnte aufkommen, falls man z.B. eine bestimmte Anzahl zu füllender Elemente erzwingen möchte, wenn ein spezifisches Layout das erfordert. Momentan greifen Min/Max-Werte erst, wenn vom Nutzer entsprechend viele Blöcke angelegt wurden – es ist also nicht gewährleistet, dass am Ende die benötigte Anzahl an Blöcken erreicht wird.

**Ansätze:**
- evtl. automatische Berücksichtigung des Min-Werts bei der Neu-Anlage
- oder unabhängiger Parameter mit Angabe der anzulegenden Block-Anzahl (start-count)

Wir hatten die Frage gerade im Slack diskutiert und wollten das als Idee für später hier festhalten.

**Comment by skerbis** [comment]
sollte eigentlich der fall sein wenn min und max gesetzt sind in mform8

**Comment by ischfr** [comment]
Momentanes Verhalten:
Wenn man z.B. Min:3 hat und der User legt 5 Einträge an, kann er anschließend nur 2 löschen.
Wenn er aber nur 2 anlegt, wird Min:3 gar nicht erst erreicht und greift deshalb (noch) nicht.
Falls z.B. das Layout auf mind. 3 Einträge angewiesen ist, hätte man erst mal ein Problem.

Wir hatten hier im Slack darüber gesprochen: 
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1714469153717679?thread_ts=1714381836.438389&cid=C1BAXLN2F

**Comment by joachimdoerr** [comment]
Tatsächlich ist die Umsetzung ziemlich schwierig. Jedenfalls ist mir beim drüber schauen noch kein "einfacher" Ansatz eingefallen. Für solchen Fällen könnte man auch mit preSaveAction eine Validierung einrichten.
