### ISSUE TITLE
Beispiel Code nicht formatiert

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mform#327]
Alles aktuell...

![image](https://github.com/FriendsOfREDAXO/mform/assets/330516/db755fbb-0c7a-416a-b4e7-d12a59e0f4d9)

**Comment by joachimdoerr** [comment]
@olien  ich kann das Problem bei der aktuellen Beta nicht bestätigen, was nutzt Du für ein Browser?
<img width="965" alt="Bildschirmfoto 2024-05-13 um 22 34 01" src="https://github.com/FriendsOfREDAXO/mform/assets/1191549/b9c72f14-c732-4de7-8eb7-0cc5b4ac3c64">

**Comment by skerbis** [comment]
<img width="1608" alt="Bildschirmfoto 2024-05-16 um 10 50 18" src="https://github.com/FriendsOfREDAXO/mform/assets/791247/b6402f45-bdce-4ab0-bf15-d21c5762ad77">
