### ISSUE TITLE
Codebeispiele und neuer Namespace?

### ISSUE THREAD

**Issue by ischfr** [FriendsOfREDAXO/mform#331]
In der Beta 7 gibts im Changelog den Hinweis:

> IMPORTANT: breaking namespace change -> from MForm to FriendsOfRedaxo\MForm

Müsste das nicht auch bei den Codebeispielen berücksichtigt werden, damit die weiterhin funktionieren?

**Comment by skerbis** [comment]
ja

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/d7f666c6754e1e97d940ad166407c77df8275e38
