### ISSUE TITLE
MForm 8 Beta – Repeater mit CKE5 in zweiter Ebene

### ISSUE THREAD

**Issue by ischfr** [FriendsOfREDAXO/mform#332]
**Nutzung von CK-Editor 5 (Addon Version 6.1.0) im Repeater:**

In der ersten Repeater-Ebene funktioniert das Umsortieren von Repeater-Einträgen unter Mitnahme der CK-Editor-Inhalte. 
Das ging in frühen Beta-Versionen anfangs nicht, wurde dann aber gefixt.

In der zweiten Ebene funktioniert das Umsortieren in der aktuellen Version (8.7Beta) noch nicht. 
Das verhält sich wie vor dem Fix bei der ersten Ebene: 
Die Editor-Inhalte werden nach dem Sortieren nicht an der neuen Position angezeigt, sie wandern nicht mit. 
Sie werden dann aber trotzdem mit dem richtigen Eintrag gespeichert.

Das Verhalten wurde vor kurzem auf Slack erwähnt und bestätigt – ich spreche es hier noch einmal an, damit es nicht untergeht.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/7979f599badba3b33c570a8b4faeae0ae6015f36

**Comment by ischfr** [comment]
Das Sortieren der zweiten Ebene scheint nun zu funktionieren. Aber beim Sortieren der ersten Ebene kriege ich nun in der Browserkonsole Fehlermeldungen in Verbindung mit cke5.

```
CKEditorError: can't convert null to object
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-can't convert null to object
```
Ausserdem ist am Ende eines Blocks nun ein leeres Textfeld zu sehen, in dem wohl die Repeater-Inhalte verwaltet werden.

**Comment by ischfr** [comment]
Hab es gerade noch mal mit einer neueren Version probiert. Die Konsolen-Fehlermeldungen beim Umsortieren der 1. Ebene sind nun verschwunden.

Das zusätzliche Textfeld mit den Repeater-Inhalten ist auch wieder unsichtbar.
