### ISSUE TITLE
Repeaterfarben im DarkMode sehr dunkel

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mform#337]
![image](https://github.com/FriendsOfREDAXO/mform/assets/330516/8043417a-10d9-4f85-bb17-1ca08f1cae21)

**Comment by eaCe** [comment]
Ein Vorschlag von mir dazu:

![grafik](https://github.com/FriendsOfREDAXO/mform/assets/2708231/bf400c6e-2472-4a79-b829-423dd6e420d1)

**Comment by olien** [comment]
👍

**Comment by skerbis** [comment]
@eaCe hast es schon gemacht ?

**Comment by eaCe** [comment]
@skerbis nein, mach ich gleich.

**Comment by skerbis** [comment]
Danke
