### ISSUE TITLE
Sortierung funktioniert nur nach Speicherung

### ISSUE THREAD

**Issue by georgkaser** [FriendsOfREDAXO/mform#353]
**Description / Beschreibung**

Vielleicht habt ihr das eh schon auf dem Schirm - ich mach trotzdem mal einen Eintrag. Wenn ich die Blöcke beim Repeater verschiebe, dann tut sich nichts. Erst nachdem ich zwischenspeichere, werden die Blöcke richtig sortiert. Siehe hier:

https://github.com/user-attachments/assets/826a43c3-4939-4403-bb62-8c510229516b

Aja, cool wäre auch, wenn man das wieder per drag&drop verschieben könnte. Und was ganz schlimm fehlt sind die + Buttons zwischen den Blöcken. Die waren auch bei MBlock schöner und größer.

**Affected versions / Verwendete Versionen**

REDAXO: 5.17.1
PHP: 8.2.21 
Database: MariaDB 10.11.8
Browser: Chromium Version 126.0.6478.126 (Offizieller Build) Fedora Project (64-Bit)
AddOns: mform 	8.0.3

**Did it whoops? / Whoops erhalten?**

nope

**Comment by skerbis** [comment]
Kann ich nicht reproduzieren.
