### ISSUE TITLE
Tabs integrieren

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mform#63]
Tabs z.b. Bootstrap Tabs oder jQuery UI Tabs - sollte nach dem selben Prinzip wie fieldsets integriert werden.

**Comment by joachimdoerr** [comment]
wird erstmal nicht umgesetzt.

**Comment by RexDude** [comment]
Hmm wirklich sehr schade. Tabs sind für mich mittlerweile unverzichtbar in Modulen und gehören mMn zu einer guten Usability hinzu. Die Umsetzung sollte sehr simple sein zumal ja mit Bootstrap Tabs Unterstützung im Backend exisitiert. Auch sollte die API analog zu den Fieldsets sein, d.h. hier muss man net wirklich viel tun :)

Bitte? :)

**Comment by RexDude** [comment]
So soll das Markup ausschauen am Ende. Das JS ist dafür die Tabposition zu speichern bei reload. Evtl. kann ich ja gerne auch irgendwie mithelfen beim umsetzen...

```html
<script>
$('a[data-toggle="tab"]').on("shown.bs.tab", function (e) {
    var id = $(e.target).attr("href");
    localStorage.setItem('selectedTab', id)
});

var selectedTab = localStorage.getItem('selectedTab');
if (selectedTab != null) {
    $('a[data-toggle="tab"][href="' + selectedTab + '"]').tab('show');
}
    </script>

<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">...</div>
    <div role="tabpanel" class="tab-pane" id="profile">...</div>
    <div role="tabpanel" class="tab-pane" id="messages">...</div>
    <div role="tabpanel" class="tab-pane" id="settings">...</div>
  </div>

</div> 
```

**Comment by joachimdoerr** [comment]
Das sollte man ähnlich wie Vieldsets umsetzen können. Ich müsste mir das mal gründlich überlegen. Es schon schick ;-)

**Comment by joachimdoerr** [comment]
nice ;)

**Comment by RexDude** [comment]
thx :))

**Comment by RexDude** [comment]
btw: dass musst ich korrigieren weil sonst der html parser probleme bekam. ich vermute es kommt von mform: https://github.com/RexDude/xcore/blob/master/lib/rexx.php#L403-L404

**Comment by joachimdoerr** [comment]
Ich prüfe das mal `selected` und `checked` werden nicht durch MForm im MBlock gesetzt sondern von MBlock selbst da das ja durch das rex_json aufgeteilt werden muss auf die einzelnen Blöcke.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/09a62f8a69d2c00d27065b66d88e72aa899a36a9

**Comment by RexDude** [comment]
Sauber Joachim! Habs grad getestet und läuft super. closeTabs wird auch nicht gebraucht. Position wird auch gespeichert. Top!
Dankeschön für das nette Geschenk :)
