### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/mform#65]
Hi,
wie wärs denn mit einem Colorpicker als fertiges Element? Fänd ich ganz praktisch.

**Comment by joachimdoerr** [comment]
Für ein hidden Input Field?

**Comment by omphteliba** [comment]
Gute Idee!

**Comment by joachimdoerr** [comment]
Ich finde das zu spezifisch, ich denke das kann man auch ohne eigene MForm Methode auf ein Hidden-Input oder Text-Feld anwenden lassen. Dazu muss man ja nur eine ID oder Data-Tag via Attribute setzen und dann per Javascript das Color-Picker Plugin auf das Eingabefeld initiieren.

**Comment by omphteliba** [comment]
Joah, magst Du ja gerne so sehen, aber der HTML-Color Picker ist unter Windows für den Arsch. Und das andere Gefummels das Du vorschlägst gilt - meines Erachtens - für das ganze Mform. Ich habe fast in jedem Modul ein Farbauswahlfeld in dem mindestens eine - wenn nicht mehrere - Hex-Auswahlen erwartet werden. 

Fü mich ist das wie wenn es kein Text-Auswahlfeld im Mform gäbe.

**Comment by IngoWinter** [comment]
Joachim schlägt kein _Gefummels_ vor, sondern dass du einem Textfeld ein Attribut mitgibst, welches das Colorpicker Script deiner Wahl triggert. Zb könntest du eine Klasse `colorpicker` mitgeben. Dann lädtst du im Backend das [Colorpicker Script](https://bgrins.github.io/spectrum/) und gut ist. 
```
<script src="/dein/pfad/spectrum.js"></script>
<link rel="/dein/pfad/stylesheet" href="spectrum.css" />
<script>$(".colorpicker").spectrum();</script>
```

Du solltest dir mehr Zeit für die Formulierung deiner Kommentare nehmen - deine Einordnung von Joachims Vorschlag als _Gefummels_ lässt dich rotzig/ inkompetent erscheinen.

**Comment by omphteliba** [comment]
> Du solltest dir mehr Zeit für die Formulierung deiner Kommentare nehmen - deine Einordnung von Joachims Vorschlag als Gefummels lässt dich rotzig/ inkompetent erscheinen.

Ih weiss nicht was das hier zu suchen hat.

**Comment by IngoWinter** [comment]
Gern geschehen!
