### ISSUE TITLE
Leer-Option für select sql

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#66]
Hallo!

Gibt's denn die Möglichkeit, neben den Auswahl-Möglichkeiten eine leere Option anzuzeigen?

**Comment by joachimdoerr** [comment]
''=>'' im array sollte das gewährleisten

**Comment by alexplusde** [comment]
Das heißt aber, ich müsste eine leere Datenbank-Zeile haben?

**Comment by joachimdoerr** [comment]
Hm für Datenbanken ist das so eine Sache

**Comment by phoebusryan** [comment]
Wovon ist genau die Rede? Würde nicht ein UNION ALL helfen?

**Comment by joachimdoerr** [comment]
Es gibt in MForm ja die Möglichkeit ein SQL Form-Select zu nutzen - die Options des Formular-Element kommen dann aus dem DB SELECT aber das Formular-Select kann dann aktuell keine leere Option haben.

**Comment by phoebusryan** [comment]
Ja genau. Aber du wrappst ja lediglich die Redaxofunktioanlität.. Insofern sollte ein UNION ALL das Problem doch lösen?

**Comment by alexplusde** [comment]
Ich möchte die Auswahl optional machen. Inwieweit hilft da UNION ALL?

**Comment by phoebusryan** [comment]
Poste mal den Code, womit du das Selectfeld generierst.

**Comment by alexplusde** [comment]
```
$team_sql = rex_sql::factory()->getArray('SELECT id, name FROM rex_yf_staff WHERE active > 0');
$team = [];
$team[' '] = "Bitte wählen"; // Leer-Option
foreach($team_sql as $person) {
    $team[$person['id']] = $person['name']; 
}
$mform1->addSelectField("1.0.id", $team, 'Mitarbeiter');
```

**Comment by phoebusryan** [comment]
dann probier mal folgendes:

$team_sql = rex_sql::factory()->getArray('SELECT null as id, null as name UNION ALL SELECT id, name FROM rex_yf_staff WHERE active > 0');

... wobei 'null' natürlich z.b. auch durch 'Bitte wählen' ersetzt werden kann.

**Comment by alexplusde** [comment]
Klar, das ist eine ähnliche Umgehung des fehlenden Parameters. Mein Issue zielt ja darauf ab, die Leer-Option gezielt als Parameter angeben zu können, wie es bspw. bei YForm-Feldern der Fall ist.

**Comment by joachimdoerr** [comment]
Naja MForm hat ja die Methode `addSqlOptions` dieser sollte man nur eine SQL Query übergeben. Hier wäre dann ein zusätzlicher Parameter denkbar der dann die Nulloption einsetzt.

**Comment by tbaddade** [comment]
Ich hatte da mal ein Gist. Ist zwar für den XForm-Formbuilder aber der Query könnte dennoch passen.

https://gist.github.com/tbaddade/8932602

**Comment by phoebusryan** [comment]
... scheint als wäre ein UNION ALL also immernoch die 'richtige' Lösung.

**Comment by alexplusde** [comment]
Heißt jetzt für das Issue? Wontfix? Doku?

**Comment by phoebusryan** [comment]
Es heisst, dass es nichts mit dem Addon mform zu tun hat. man sollte dies wenn im Core lösen. :)

**Comment by tbaddade** [comment]
> man sollte dies wenn im Core lösen

Inwiefern im Core? Wenn dann müsste es m.E. MForm lösen.
Eine Leeroption via rex_select kannst du mit `addOption()` vor dem `addSqlOptions()` erzeugen.

**Comment by joachimdoerr** [comment]
Es wäre schon sinnvoll wenn man `addSqlOptions` ein zusätzlichen Parameter erhalten täte um diese Leer-Option voranzustellen.

**Comment by phoebusryan** [comment]
Core weil man das Problem überall hat. auch mit rex_form im Backend etc. Aber addOption() und addSqlOption() zu kombinieren ist tatsächlich eine gute Lösung!

**Comment by tbaddade** [comment]
@phoebusryan Ich mache ab und zu sogar auf ein select mehrere `addSqlOption` oder wenn man optgroup arbeiten will. Mann kann auch mehrere `addOption` verwenden.

**Comment by phoebusryan** [comment]
@tbaddade das ist cool. wusste nicht, dass man das alles so kombinieren kann! :)

**Comment by joachimdoerr** [comment]
Ich denke das nehmen wir in die Doku auf, Quelltext Änderungen sind mit der Lösung von Thomas somit eigentlich nicht mehr nötig.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/483a0857f164dcb4010f605722b79f2d414c43ba
