### ISSUE TITLE
Ausgabe "block" im Backend

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#68]
Was hat es damit auf sich?
![image](https://cloud.githubusercontent.com/assets/3855487/16038456/4edd1692-3225-11e6-81e0-70e885c31e85.png)

![image](https://cloud.githubusercontent.com/assets/3855487/16038476/601cbec6-3225-11e6-9725-22d45e822b91.png)

**Comment by joachimdoerr** [comment]
Man kann ja in MForm eigene Formular-Templates Definieren. Das ganze müsste nur mal genau beschrieben werden, ist noch sehr roh.

**Comment by alexplusde** [comment]
Kann man dich da irgendwie unterstützen?

**Comment by joachimdoerr** [comment]
Ja gerne doch!

**Comment by alexplusde** [comment]
Wie? :D sollen wir dazu mal skypen?

**Comment by joachimdoerr** [comment]
Klar bist du im Slack? http://www.redaxo.org/slack/

**Comment by joachimdoerr** [comment]
Der Text "block" muss weg. Keine Ahnung wie der da hinkommt, für den nächsten Release ist das zu entfernen.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/23c683d8ac09e04e4892a34ed49769b511c538b6
