### ISSUE TITLE
HowTo Eigene Themes / schöneres default Theme

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#69]
In Redaxo4 hatte mform ja ein eigenes Layout, was ich sehr angenehm und aufgeräumt fand.

![image](https://cloud.githubusercontent.com/assets/3855487/16081652/b42f7276-330e-11e6-8603-46ef0f63166d.png)

Unter Redaxo5 wirkt das, gerade mit den Überschriften und der Description, etwas verloren

![image](https://cloud.githubusercontent.com/assets/3855487/16081594/7f395bc2-330e-11e6-818b-18d409ebc4e5.png)

Brauchst du da Unterstützung? Wie funktioniert das mit den eigenen Themes an der Stelle?

**Comment by joachimdoerr** [comment]
Die Themes sind in einem Folder abgelegt, da hat es dann Template Files fürs HTML und eine CSS Datei für den Style. Ich hatte für R5 so meine Mühe da extrem viel auf inline classes gesetzt wird, mit Vererbung is da nix... und mfrom hatte im R4 DefaultTheme viel mit Vererbung gearbeitet.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/tree/master/templates/default_theme

duplizier einfach /templates/default_theme zu /templates/dein_theme und pass alle Dateien entsprechend deiner Wünsche an.

**Comment by alexplusde** [comment]
Evtl. kann unser Azubi ein Theme beisteuern, das sich am aktuellen Redaxo-CSS orientiert. 
Ich werde mal fragen, ob er Zeit dafür bekommt. Falls es dir zusagt, würdest du es als alternatives Theme mitliefern?

**Comment by nilsology** [comment]
Vielleicht wäre hier eine Idee Bootstrap-Form-Magic zu implementieren.

Idee am Rande: Tabs, wie man Sie momentan [noch manuell bauen muss](https://getbootstrap.com/javascript/#tabs-examples).

Funktionsvorschlag:

``` php
$objForm = new mform();
$objForm->newTab(1, array(
  'label' => 'Tab 1' // => href = return strtrolower(strip($label))
));

$objForm->addTextfield(1); // or whatever

echo $objForm->show();
```

``` html
<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab">Tab 1</a></li>
    <!-- ... -->
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="tab 1">
        <input name="REX_INPUT_VALUE[1]" ...>
    </div>
    <!-- ... -->
  </div>
</div>
```

**Comment by joachimdoerr** [comment]
@nilsology Tabs wollte ich ja integrieren aber momentan hatte erstmal die neue Code-Basis Vorrang. https://github.com/FriendsOfREDAXO/mform/commit/a666ab70e1add89fe571db9bf7453358a4a7cef7

**Comment by joachimdoerr** [comment]
Für 5.1.0 könnten wir ein zweites theme in MForm anbieten.

**Comment by alexplusde** [comment]
Auch in diesem Issue fürs Protokoll: Dass es die Modul-Eingabe bei mir zerhauen hat, lag daran, dass man nach der Installation zwingend erst ein Theme in den Einstellungen wählen muss und immer fieldsets verwendet.

**Comment by DanielWeitenauer** [comment]
Hi,
cool wäre, wenn man den Pfad zum Template frei wählen könnte.

Mit einem EP am Ende von MFormThemeHelper::getThemesInformation() à la
```
    $themeInfo = rex_extension::registerPoint(new rex_extension_point('MFORM_THEME_ARRAY', $themeInfo));

    // return theme info array
    return $themeInfo;
}
```
lässt sich leicht ein Array mit den benötigten Daten einfügen. 

Da im PathProvider allerdings vom Data Ordner als Root ausgegangen wird, muss man den Pfad z.B. zum Ordner des Theme-Addons noch so angeben:
```
../../../../../theme/etc.
```
Gäbe es da die Möglichkeit, den Basis-Ordner der Installation als Referenz zu nehmen?

**Comment by joachimdoerr** [comment]
Ja in Hinblick auf Page oder Theme addon oder auch eigene Bachend Theme Plugins/Addons wäre da ein flexibleres Handling gar nicht schlecht.

**Comment by joachimdoerr** [comment]
ich schließe mal da das Problem in eher durch fehlende fieldsets entstand. Den erste Betreffend MForm Themen sollte man mal gesondert überlegen.
