### ISSUE TITLE
Feature: HTML5 Input Types

### ISSUE THREAD

**Issue by nilsology** [FriendsOfREDAXO/mform#70]
- search
- email
- url
- tel
- number
- range
  - attr: min, max, step, list
- date
- month
- week
- time
- datetime
- datetime-local
- color

@alexplusde noch irgendwelche Ideen?

Vorschlag:

``` php
$objForm = new mform();

$objForm->addRangeField(1, array(
  'min' => '1',
  'max' => '10',
  'label' => 'range with min/max'
));

$objForm->addRangeField(2, array(
  'label' => 'range with datalist'
));

$objForm->addDataList([0, -30, 30, 50]);

echo $objForm->show();

```

``` html
<input type="range" name="REX_INPUT_VALUE[1]" min="1" max="10">
<input type="range" name="REX_INPUT_VALUE[2]">
<datalist id="powers">
  <option value="0">
  <option value="-30">
  <option value="30">
  <option value="+50">
</datalist>

```

**Comment by alexplusde** [comment]
@nilsology gut vorgelegt, im Moment keine weiteren Ideen.

Deine Vorschläge könnten aber auch bei YForm Berücksichtigung finden, wir hatten auf dem Redaxo-Tag mal überlegt, ein input="date"-Kalenderfeld zu integrieren. Muss wohl gar nicht so schwer sein, einfach das bestehende text-input-Feld Template abzuwandeln.

**Comment by joachimdoerr** [comment]
Eine sinnvolle Erweiterung, ich plane das mal für den nächsten Release ein.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/blob/master/pages/examples/expert1_html5_form_elements.ini
https://github.com/FriendsOfREDAXO/mform/blob/master/pages/examples/expert2_datalist.ini

**Comment by ynamite** [comment]
Leider funktioniert das Ganze im aktuellen Release nicht mehr. In der Version 5.1.0 hatte ich folgendes:

```$mform->addInputField("date", 1, array('label'=>'Datum')); 
```

Hat prima funktioniert. Nach dem Update auf 5.2.2 funktionieren bei mir keine der HTML5 Input-Elemente mehr. Mach ich etwas falsch? Hab 1:1 die Beispiele kopiert.

**Comment by alexplusde** [comment]
Selbes Problem hier...

**Comment by joachimdoerr** [comment]
sollte nun funktionieren. bitte mit der aktuellen master testen.

**Comment by skerbis** [comment]
Getestet 👍

**Comment by alexplusde** [comment]
@ynamite kannst du das testen, ich kann es gerade nicht...

**Comment by joachimdoerr** [comment]
@skerbis kannst du das bitte releasen, ich komme nicht dazu.

**Comment by skerbis** [comment]
Japp.
