### ISSUE TITLE
Templates für Form Elemente

### ISSUE THREAD

**Issue by christophevouillamoz** [FriendsOfREDAXO/mform#71]
In meinem Fall stört mich die Klasse form-horizontal auf dem Fieldset. Diese hat einfluss auf das Styling und im theme.css würde ich ungern die Standart Funktionalität von Bootstrap überschreiben. Wäre toll könnte man pro Form Element (fieldset, text input, textarea, checkbox, etc) ein Template haben.

**Comment by joachimdoerr** [comment]
Das macht durchaus Sinn, ich wollte so oder so die template engine etwas anpassen und ergänzen.

**Comment by joachimdoerr** [comment]
```
$mform->addFieldset('Fieldset Headline');
$mform->setAttribute('default-class', false);
```
https://github.com/FriendsOfREDAXO/mform/commit/a666ab70e1add89fe571db9bf7453358a4a7cef7
