### ISSUE TITLE
theme.css wird nicht immer geladen

### ISSUE THREAD

**Issue by christophevouillamoz** [FriendsOfREDAXO/mform#72]
Wenn man ein Block editieren möchte wird das theme.css nicht geladen, womöglich weil nicht die ganze Seite neu geladen wird.

Gemäss boot.php wird die Datei eingebunden wenn
`if (rex_request('function', 'string') == 'edit' or rex_request('function', 'string') == 'add')`

Ich denke es wäre besser wenn es immer geladen wird im Backend. Man hat zwar einen Request mehr aber sobald es im Cache ist geht es wieder schneller. Dank dem mform_wrapper.ini kann man so ein Namespace für das Formular definieren und die CSS Deklarationen innerhalb des Namespaces definieren so dass diese mit dem Redaxo Interface nicht interferieren.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/23c683d8ac09e04e4892a34ed49769b511c538b6
