### ISSUE TITLE
Templates besser verwalten

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mform#73]
Um eigene custom Templates in MFrom einspielen zu können muss man das von hand in den Folder "templates" kopieren. https://github.com/FriendsOfREDAXO/mform/tree/master/templates

Das ist recht unflexibel, es wäre besser Templates besser verwalten zu können. 

Wer hat Idee? Ich bin da für alles offen.

**Comment by christophevouillamoz** [comment]
Ich würde die Templates über den data Ordner verwalten damit ein Update des Addons möglich ist ohne dass die Templates gelöscht werden.

**Comment by joachimdoerr** [comment]
Genau daran hatte ich auch gedacht.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/29ca6f2170a6554a9195f5fb064a6d50b7f349dd
https://github.com/FriendsOfREDAXO/mform/commit/8d6d9ac7e68900f5ac7799bef7910da786daf1ef
https://github.com/FriendsOfREDAXO/mform/commit/65920a64b43d04003d6a554c442aa488c4f8779b
