### ISSUE TITLE
Wunsch: Clientseitige Validierung (und Parameter dafür in mform)

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#78]
Wie in Slack besprochen hier als Issue :)

**Comment by joachimdoerr** [comment]
Parsley ist ja schon enthalten, funktioniert nur nicht konsistent wegen dem ajax load, hier müsste ein callback genutzt werden um parsley auf den geladenen DOM anwenden zu können.

**Comment by joachimdoerr** [comment]
Parsley 2 ist drin, ajax initialize problem ist behoben.

https://github.com/FriendsOfREDAXO/mform/commit/991ae5ecfa2bb3e9afab6623515fd6e190554eb7
