### ISSUE TITLE
Wunsch: Doku um Modulausgabe ergänzen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#79]
Was ich in der Hilfe gut fände, wäre ein Absatz darüber, wie man auf alle Werttypen in der Ausgabe zugreift (REX_MEDIALIST[], REX_VALUE[1] etc.)  Da gibt's doch auch die Möglichkeit, mehrdimensionale Values anzulegen. Keine Ahnung, wie :D

**Comment by joachimdoerr** [comment]
Ja kann man machen, jedoch ist MForm eigentlich nur für den input da nicht für den Modul output

**Comment by joachimdoerr** [comment]
Hierdurch ist es möglich in den Beispielen auch Modulausgaben zu erfassen: 
https://github.com/FriendsOfREDAXO/mform/blob/master/pages/demo.demo_base.php#L32-L35

Das Problem ist jetzt nur noch die Fleißarbeit.

**Comment by cukabeka** [comment]
GIbt es denn ein Beispiel für REX_VALUE[1.2], wie dann die Ausgabe aussähe? Dann wäre mindestens 1 Beispiel schön.

**Comment by DanielWeitenauer** [comment]
@cukabeka Da gibt es keinen Unterschied zu normalen mehrdimensionalen REX_VALUE: https://redaxo.org/doku/master/redaxo-variablen
