### ISSUE TITLE
Begrifflichkeiten / Konsistenz / i18n

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#80]
Die Seite "Einstellungen" heißt bisher "Settings" und könnte platztechnisch eigentlich mit der 1. Seite "Info" zusammengefasst werden, die bei anderen Addons meist "Übersicht" heißt.

Generell hätte ich vorgeschlagen, die Labels, Texte, etc. in eine lang-Datei zu packen und englische Begriffe einzudeutschen, bspw.
Template-Theme -> Theme in der Modul-Eingabe 
Default-Theme -> Standard

**Comment by joachimdoerr** [comment]
Ja die Info und Settings könnten wir zusammen führen.
Sprachlich seh ich keine dringliche Notwendigkeit auch wenn es sinn macht. Wenn du möchtest kannst du hier ein pull request dazu anlegen.

**Comment by joachimdoerr** [comment]
Text Label : ja ist geändert
Text Select Option: nein geht so nicht -> wird durch Folder name vom Template erzeugt
Zusammenführen von Config und Info in Übersicht ist erledigt.

https://github.com/FriendsOfREDAXO/mform/commit/59c5da565ff2382ecb2c4c7327f3341b70ac745e
https://github.com/FriendsOfREDAXO/mform/commit/db29fba6dd4fc37d9acd858bcfcfe8ee27ff217d
