### ISSUE TITLE
Seite "Einstellungen" in Bootstrap-Markup

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#81]
![image](https://cloud.githubusercontent.com/assets/3855487/16830891/f9dd6040-49a1-11e6-8ab8-865233b8494e.png)

Template-Dropdown und Button ist nicht ans Bootstrap-Design vom Redaxo-Backend angepasst.

**Comment by joachimdoerr** [comment]
Guter Hinweis!

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/b2bd499ef522477b6177967fe2b8ca71ca2bebc0
