### ISSUE TITLE
GitHub: Links zum Wiki (und zu den 4./5.-Repos) sind verkehrt.

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#82]
Beim Wiki kommt das leere Wiki der FOR-Repo.

**Comment by joachimdoerr** [comment]
Die Links im Wiki selbst sind jeweils korrigiert, die größten Schnitzer im Wiki aus alter zeit sind korrigiert, generell müsste das Wiki mal überarbeitet werden.

In MForm Info ist die Links korrigiert und zeigen nun auf FOR:
https://github.com/FriendsOfREDAXO/mform/commit/8e47480c004424ebfe520a552f82dfdefdf1f440
