### ISSUE TITLE
Consolen-Fehler zu default_theme/theme.css

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#83]
```
file_get_contents(/kunden/322541_70190/alexplus.de/kulturkeller_rex5/redaxo/src/addons/mform//templates/default_theme/theme.css): failed to open stream: Datei oder Verzeichnis nicht gefunden	
```

spammt mir die System-Konsole voll

**Comment by joachimdoerr** [comment]
Thanks bins grade am fixen wird in v5 behoben sein

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/cc7b4b9155a70cd267d96643fb7ee2ea664b9106
https://github.com/FriendsOfREDAXO/mform/commit/ae516fcdb4cdf56165d2e3274c38985b00ec1880
https://github.com/FriendsOfREDAXO/mform/commit/764e02bb82220fde077400d98983718f65a5c0a8
