### ISSUE TITLE
Themewähler im Backend funktioniert nicht

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/mform#84]
Ich habe unter `/redaxo/data/addons/mform/templates/iw_theme` ein eigenes Theme hinterlegt. Das Theme steht im Backend zur Auswahl und lässt sich speichern. Allerdings wird es nicht angewendet sondern immer das default_theme genommen.
Lade ich das Theme beim so: `$mform = new mform('iw_theme');` funktionierts. Ich nehme also an, das in der config gespeicherte Theme wird einfach nirgendwo gesetzt.

**Comment by joachimdoerr** [comment]
Danke für den Hinweis, muss ich checken was da los ist.

**Comment by IngoWinter** [comment]
Ich habe 4.2.3, über den Installer gezogen. Vielleicht war das der Fehler ^^

**Comment by joachimdoerr** [comment]
Jep mit MForm 5 müsste das alles passen ;)

**Comment by IngoWinter** [comment]
Kann ich bestätigen :)
