### ISSUE TITLE
Darstellungsfehler aktuelle Beta

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#85]
![image](https://cloud.githubusercontent.com/assets/3855487/17478700/f1e3e942-5d6d-11e6-9ba9-dc863ed48228.png)

**Comment by joachimdoerr** [comment]
Ich kann das leider nicht nachstellen. Hast du ein Zugang für mich, dass ich mir das mal direkt anschauen kann?

**Comment by joachimdoerr** [comment]
Ok Danke für das Beispiel. Für Redaxo Formulare immer Fieldsets nutzen, sonst schauen die Formulare genauso aus.

`$mform->addFieldset('Team member');`

**Comment by alexplusde** [comment]
dann wäre es gut, gleich in den Beispiel-Modulen darauf hinzuweisen... auf mich wirkte die Option für ein Fieldset eher als "optional".

**Comment by joachimdoerr** [comment]
Das kann man schon machen aber das ist definitiv ein "Redaxo Problem". Der Modul Style wird von MForm nicht manipuliert, da kommt reines Redaxo Bootstraping zum Einsatz.

**Comment by alexplusde** [comment]
Wäre es möglich, dass ein fieldset ohne legend ausgegeben wird, wenn man `$mform->addFieldset('');` setzt? Im Moment muss ich mir Zwischenüberschriften ausdenken, oder mit einem Strich durch das leere Legend-Feld leben.
