### ISSUE TITLE
Einfache Checkbox ermöglichen

### ISSUE THREAD

**Issue by rolandsee** [FriendsOfREDAXO/mform#86]
Bisher ist es mit rex_form nicht möglich, mit einer einfachen Checkbox einen Status z.B. mit 0 und 1 zu speichern. Das checkbox-feld ist immer auf mehrere Optionen ausgelegt. Alternativ bietet sich dazu das select an, welches jedoch an dieser Stelle dann doch etwas zweckentfremdet ist.
Die einfache Checkbox war wohl schon mal angedacht, wurde jedoch noch nicht umgesetzt.

**Comment by joachimdoerr** [comment]
Das wäre ein Task für den Redaxo Core, MForm bietet ja Checkbox an.

**Comment by alexplusde** [comment]
In der Datenbank wird bei rex_form der Wert mit Tilden getrennt gespeichert. Wie kommst du denn bisher an den Wert? Du kannst ja bspw. mit `str_replace("|", "", $checkbox);` die `|` eleminieren.

Aber, wie @joachimdoerr schreibt: Hat nichts mit mform zu tun.
