### ISSUE TITLE
Nach Update auf mForm 5 verschwinden die Eingabeformulare

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/mform#88]
Redaxo: 5.2.0 / mform 5.0.0-beta-3

Wenn ich von mform 4.2.3 auf 5.0.0-beta-3 upgrade verschwinden die Eingabeformulare meiner Slices.

Es geht nach dem klick auf das Editiern Icon die Editor Ansicht des Slice auf, aber es erscheinen die INPUT etc. Felder nicht mehr.

**Comment by joachimdoerr** [comment]
kannst du mir da mal ein Zugang zum Projekt geben.

**Comment by McAdam92** [comment]
Habe das selbe Problem ebenfalls Redaxo 5.2.0 / mform 5.0.0-beta-3

**Comment by joachimdoerr** [comment]
@McAdam92 nach dem mform update von 4.x auf 5.x

**Comment by joachimdoerr** [comment]
@omphteliba @McAdam92 wie schaut denn euer Modul-Output aus?

**Comment by omphteliba** [comment]
@joachimdoerr sorry, das Projekt lebt auf einem Server ohne DNS Eintrag.

Der Modul-Output ist gleich geblieben.

**Comment by omphteliba** [comment]
Seltsam: wenn ich eine neue Seite anlege, dann erscheint das Eingabeformular für die Slices.

**Comment by omphteliba** [comment]
Also bei mir geht's jetzt plötzlich wieder... Seltsam.
