### ISSUE TITLE
addDescription formatieren

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mform#90]
analog zu yform:

![image](https://cloud.githubusercontent.com/assets/3855487/21548273/ab911cc8-cdeb-11e6-81ea-9a638a15b837.png)

```
$mform1->addHtml('<p class="help-block">Die ID befindet sich in der Adresszeile, z.B. <code>https://www.youtube.com/watch?v=<strong style="color: black;">2vwAVYaItEA</strong></code>.</p>');
```

**Comment by joachimdoerr** [comment]
Ja das würde sinn machen ggf. sollte man die Möglichkeit haben welche art von description man hinzufügen möchte und verschiedene Darstellungen anbieten.

**Comment by alexplusde** [comment]
http://getbootstrap.com/components/#alerts vlt?

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/5c40292494e736bc747d7cd78af0ba4f1a2e38fa
