### ISSUE TITLE
Aktuelle Experten Beispiele (rexday)

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/mform#93]
Im aktuellen release (installer) fehlen die Experten Beispiele z.b. validation

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/blob/master/pages/examples/expert4_validation.ini

die Beispiele scheinen da zu sein.

**Comment by joachimdoerr** [comment]
Beispiele sind drin.
