### ISSUE TITLE
Fehlerhafte Einrückung addHeadline/addDescription

### ISSUE THREAD

**Issue by shauste** [FriendsOfREDAXO/mform#94]
Innerhalb eines Fieldset wird addHeadline/addDescription nicht korrekt eingerückt:
<img width="773" alt="bildschirmfoto 2017-01-16 um 16 47 11" src="https://cloud.githubusercontent.com/assets/4592113/21989559/a9b42f0c-dc0b-11e6-8d55-6d9598bac530.png">

**Comment by joachimdoerr** [comment]
Thanks.
