### ISSUE TITLE
Fieldsets Problem

### ISSUE THREAD

**Issue by RexDude** [FriendsOfREDAXO/mform#96]
Das hier:

```php
$mform = new MForm();

$mform->addFieldset('fieldset1');
$mform->addTextField(1); 
$mform->closeFieldset();

$mform->addFieldset('fieldset2');
$mform->addTextField(2);
$mform->closeFieldset(); 

$mform->addFieldset('fieldset3');
$mform->addTextField(3); 
$mform->closeFieldset();

echo $mform->show();
```

gibt wie gewünscht die 3 Fieldsets aus.

Das hier: 
```php
$mform = new MForm();

$mform->addFieldset('fieldset1');
$mform->addTextField(1); 

$mform->addFieldset('fieldset2');
$mform->addTextField(2);

$mform->addFieldset('fieldset3');
$mform->addTextField(3); 

echo $mform->show();
```

gibt auch 3 aus aber dass dritte Fieldset ist im 2. enthalten was bei mehreren Feldern dann das Layout zereisst.

Ein Bug oder?

**Comment by joachimdoerr** [comment]
Sollte nicht so sein - aber ist durchaus möglich bei der portierung von r4 auf r5 wurde daran viel angegriffen bzw. musste viel angegriffen werden - ich werde es prüfen. Wenn dann ist das ein Bug kein gewolltes verhalten ;)

**Comment by RexDude** [comment]
Dacht ich mir schon ;)
Weil ist ja eigentlich cool, dass die Fieldsets automatisch geschlossen werden :)

An dieser Stelle: danke für deinen Einsatz! MForm und Mblock sind echt toll. Mach jetzt meine Module nur noch damit :)

**Comment by joachimdoerr** [comment]
Gerne - freut mich wenn die Addons rege genutzt werden. Ich schau mir das übers Weekend an - es steht sowieso ein neuer release an, da fix ich das problem gleich mit.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/commit/c635a43ac2ec6a236ebb5e60593d6e00dc978558

**Comment by RexDude** [comment]
Danke für den Bugfix!

**Comment by joachimdoerr** [comment]
Der wird dann mit dem Release 5.1.0 ausgerollt - danke für den Bugreport ;)
