### ISSUE TITLE
Legend bei Fieldsets optional

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mform#98]
Wäre top wenn man Fieldsets auch ohne Legend-Tag anlegen kann.

FYI, Joachim hat das bereits eingebaut und muss noch getestet werden:
https://github.com/FriendsOfREDAXO/mform/commit/c635a43ac2ec6a236ebb5e60593d6e00dc978558

**Comment by joachimdoerr** [comment]
Ich muss also noch eruieren ob das entsprechende template angefasst werden muss.

**Comment by joachimdoerr** [comment]
Funktioniert ohne anpassungen am template.

**Comment by alexplusde** [comment]
In den Beispiel-Modulen sollte das fieldset noch mit dazu. (Anregung unseres Praktikanten)
